import math


def solve(num_segments: int = 5000) -> int:
    """Find number of distinct true intersection points among num_segments generated by BBS PRNG.
    
    Time Complexity: O(num_segments^2)
    Space Complexity: O(num_segments^2)
    """
    s = 290797
    MOD = 50515093

    def get_next():
        nonlocal s
        s = (s * s) % MOD
        return s % 500

    segments = []
    for _ in range(num_segments):
        x1 = get_next()
        y1 = get_next()
        x2 = get_next()
        y2 = get_next()
        segments.append((x1, y1, x2, y2))

    pts = set()

    for i in range(num_segments):
        x1, y1, x2, y2 = segments[i]
        dx1, dy1 = x2 - x1, y2 - y1
        for j in range(i + 1, num_segments):
            x3, y3, x4, y4 = segments[j]
            dx2, dy2 = x4 - x3, y4 - y3

            det = dx1 * dy2 - dy1 * dx2
            if det == 0:
                continue

            num_u = (x3 - x1) * dy2 - (y3 - y1) * dx2
            if det > 0:
                if not (0 < num_u < det):
                    continue
            else:
                if not (det < num_u < 0):
                    continue

            num_v = (x3 - x1) * dy1 - (y3 - y1) * dx1
            if det > 0:
                if not (0 < num_v < det):
                    continue
            else:
                if not (det < num_v < 0):
                    continue

            # Compute canonical reduced rational coordinates (nx/dx, ny/dy)
            num_x = x1 * det + num_u * dx1
            num_y = y1 * det + num_u * dy1

            gx = math.gcd(num_x, det)
            nx, dx = num_x // gx, det // gx
            if dx < 0:
                nx, dx = -nx, -dx

            gy = math.gcd(num_y, det)
            ny, dy = num_y // gy, det // gy
            if dy < 0:
                ny, dy = -ny, -dy

            pts.add((nx, dx, ny, dy))

    return len(pts)
