# Optimal solution generated by AI (doocs/leetcode source unavailable).
from functools import cache


class Solution:
    def goodIntegers(self, l: int, r: int, k: int) -> int:
        def count_up_to(bound: int) -> int:
            digits = list(map(int, str(bound)))

            @cache
            def dp(position: int, previous: int, tight: bool, started: bool) -> int:
                if position == len(digits):
                    return int(started)

                limit = digits[position] if tight else 9
                total = 0
                for digit in range(limit + 1):
                    next_tight = tight and digit == digits[position]
                    if not started and digit == 0:
                        total += dp(position + 1, 10, next_tight, False)
                    elif not started or abs(previous - digit) <= k:
                        total += dp(position + 1, digit, next_tight, True)
                return total

            return dp(0, 10, True, False)

        return count_up_to(r) - count_up_to(l - 1)
