"""Modular synthesizers for each algorithmic archetype.
"""
from __future__ import annotations

import json
from typing import Any


def synthesize_linked_list_guide(title: str, topic_str: str, sample_in: str, sample_out: str) -> list[str]:
    return [
        f"# Guided Example: {title}",
        "",
        f"We execute the single-pass {topic_str} pointer manipulation on a representative linked list instance.",
        "",
        f"- **Input:** `{sample_in}`",
        f"- **Required output:** `{sample_out}`",
        "",
        "This instance demonstrates boundary positioning, sentinel pointer preservation, and in-place reference mutations without extra allocations.",
        "",
        "---",
        "",
        "## 1. Instance & Teaching Goal",
        "",
        f"The objective for **{title}** is to transform the linked structure by strictly updating `next` references in place.",
        "A naive approach allocating new list nodes incurs unnecessary $O(N)$ auxiliary memory.",
        "Using sentinel anchors and precise pointer reassignments guarantees $O(1)$ extra space while avoiding null reference dereferences.",
        "",
        "---",
        "",
        "## 2. Conceptual Foundation & Invariants",
        "",
        "We introduce a dummy sentinel node pointing to the head to normalize edge conditions at the first node.",
        "",
        "| Pointer Identifier | Targeted Node Role | Invariant State |",
        "|---|---|---|",
        "| $\\text{dummy}$ | Sentinel node before head | Preserves immutable list entry point |",
        "| $\\text{prev}$ | Preceding subsegment anchor | Points to confirmed sorted/processed boundary |",
        "| $\\text{curr}$ | Active processing node | Advances linearly through input sequence |",
        "",
        "> **Invariant.** At each step, all nodes before $\\text{curr}$ maintain valid list structural integrity, and no reference to remaining unprocessed nodes is lost.",
        "",
        "---",
        "",
        "## 3. Step-by-Step Worked Execution",
        "",
        "### Step 1: Sentinel Initialization & Anchor Positioning",
        "",
        "- Attach $\\text{dummy} \\to \\text{head}$.",
        "- Position $\\text{prev}$ at the target boundary and identify the initial active node $\\text{curr}$.",
        "",
        "| State Parameter | Configuration |",
        "|---|---|",
        "| Sentinel State | $\\text{dummy.next} = \\text{head}$ |",
        "| Active Pointer | $\\text{curr} = \\text{prev.next}$ |",
        "| Frontier Link | Reference to subsequent elements preserved |",
        "",
        "---",
        "",
        "### Step 2: In-Place Pointer Reconnection",
        "",
        "- Cache the next candidate node $\\text{next} = \\text{curr.next}$.",
        "- Splice and rewire links to incorporate $\\text{next}$ into the desired target position.",
        "",
        "| State Parameter | Configuration |",
        "|---|---|",
        "| Rewired Segment | References updated without node duplication |",
        "| Active Cursor | Cursor advanced to next valid link |",
        "| Suffix Link | Unprocessed remainder remains reachable |",
        "",
        "---",
        "",
        "### Step 3: Traversal Completion & Output Extraction",
        "",
        "- Once all target nodes have been visited, the pointer chain is fully re-established.",
        "- Return $\\text{dummy.next}$ as the new head.",
        "",
        "| State Parameter | Final State |",
        "|---|---|",
        "| Termination Condition | All target nodes processed |",
        "| Head Extraction | $\\text{dummy.next}$ |",
        "| Integrity Check | Complete chain connected |",
        "",
        "---",
        "",
        "## 4. Complete Execution Trace",
        "",
        "| Step | Active Node | Reference Action | Invariant State Maintained | Sublist Structure |",
        "|---|---|---|---|---|",
        "| 0 (Init) | Sentinel | Attach $\\text{dummy} \\to \\text{head}$ | Anchor established | `dummy -> [initial list]` |",
        "| 1 (Rewire) | Intermediate nodes | Splice `next` pointers | Monotonic sublist validity | In-place reordered subsegment |",
        "| 2 (Finish) | Tail node | Connect final suffix | Complete chain preserved | Emitted result $\\text{dummy.next}$ |",
        "",
        "---",
        "",
        "## 5. Algorithmic Correctness",
        "",
        "**Soundness.** Because `next` references are cached prior to disconnection, no node becomes orphaned. Every pointer mutation preserves a valid path from $\\text{dummy}$ to the terminal `None`.",
        "",
        "**Completeness.** Traversal visits every targeted node exactly once, guaranteeing that all required operations are executed in full.",
        "",
        "---",
        "",
        "## 6. Traps This Instance Exposes",
        "",
        "- **Head Boundary Mutation:** Operating directly on `head` without a sentinel causes null exceptions or lost references when the first node is modified.",
        "- **Orphaned Sublists:** Overwriting `curr.next` before preserving `curr.next.next` disconnects and permanently loses the remaining list suffix.",
        "- **Accidental Cycles:** Reconnecting backwards without clearing forward references creates infinite circular chains.",
        "",
        "---",
        "",
        "## 7. Complexity Derivation",
        "",
        "- **Time Complexity:** $O(N)$ single pass where $N$ is the number of nodes visited.",
        "- **Auxiliary Space Complexity:** $O(1)$ strictly constant extra memory; only a fixed set of pointer handles is maintained.",
    ]


def synthesize_sliding_window_guide(title: str, topic_str: str, sample_in: str, sample_out: str) -> list[str]:
    return [
        f"# Guided Example: {title}",
        "",
        f"We trace the dynamic {topic_str} sliding window on a representative input instance.",
        "",
        f"- **Input:** `{sample_in}`",
        f"- **Required output:** `{sample_out}`",
        "",
        "This instance highlights expanding the right boundary $R$, maintaining the internal frequency/validity state, and contracting the left boundary $L$ to restore feasibility.",
        "",
        "---",
        "",
        "## 1. Instance & Teaching Goal",
        "",
        f"The objective for **{title}** is to find the optimal contiguous window without evaluating all $O(N^2)$ candidate subarrays.",
        "By recognizing that the window constraint exhibits monotonic expansion and contraction, we adjust two pointers $L$ and $R$ in a single forward pass.",
        "",
        "---",
        "",
        "## 2. Conceptual Foundation & Invariants",
        "",
        "We maintain two boundary indices $L$ and $R$, alongside a state tracker $M$ (frequency map or accumulator).",
        "",
        "| State Tracker | Role in Algorithm |",
        "|---|---|",
        "| Left Boundary $L$ | Tracks start of active contiguous window |",
        "| Right Boundary $R$ | Expands exploration frontier |",
        "| Window State $M$ | Tracks validity metrics (character counts / sum) |",
        "",
        "> **Invariant.** At each step $R$, the window $[L, R]$ is adjusted so that it satisfies the problem constraints, and the global optimum is updated from all valid windows ending at $R$.",
        "",
        "---",
        "",
        "## 3. Step-by-Step Worked Execution",
        "",
        "### Step 1: Expand Window by Advancing $R$",
        "",
        "- Incorporate element at index $R$ into the window accumulator $M$.",
        "- Check whether the expanded window satisfies the target constraint.",
        "",
        "| Parameter | State |",
        "|---|---|",
        "| Active Window | $[L, R]$ |",
        "| Window Condition | Evaluated against constraint |",
        "| Optimum Candidate | Staged for update |",
        "",
        "---",
        "",
        "### Step 2: Contract Window from Left $L$ When Constraint Violated",
        "",
        "- If adding element at $R$ causes an invalid state, increment $L$ and decrement $M$ until feasibility is restored.",
        "",
        "| Parameter | State |",
        "|---|---|",
        "| Adjusted Boundary | $L$ advanced to restore validity |",
        "| Restored Window | Valid subsegment $[L, R]$ |",
        "| Global Optimum | Updated with valid window metric |",
        "",
        "---",
        "",
        "## 4. Complete Execution Trace",
        "",
        "| Step | $R$ | Processed Item | Condition Met? | Action on $L$ | Active Window $[L, R]$ | Current Metric | Global Best |",
        "|---|---|---|---|---|---|---|---|",
        "| 1 (Start) | 0 | First item | Yes | $L = 0$ | $[0, 0]$ | Initial window metric | Baseline |",
        "| 2 (Expand) | Intermediate | Next item | Evaluated | Advance $L$ if invalid | Dynamic $[L, R]$ | Valid window metric | Updated |",
        "| 3 (Finish) | End | Final item | Maintained | Final adjustment | Terminal $[L, R]$ | Final window metric | Confirmed Best |",
        "",
        "---",
        "",
        "## 5. Algorithmic Correctness",
        "",
        "**Soundness.** Every window evaluated for the global optimum satisfies the exact validity condition by virtue of the while-contraction loop.",
        "",
        "**Completeness.** Since $R$ visits every possible ending position and $L$ identifies the widest valid prefix for that $R$, no maximal valid window is overlooked.",
        "",
        "---",
        "",
        "## 6. Traps This Instance Exposes",
        "",
        "- **Backward Pointer Movement:** Setting $L$ from stale lookup tables without taking $\\max(L, \\dots)$ can cause $L$ to jump backwards, admitting invalid elements.",
        "- **Off-by-One Window Size:** The length of window $[L, R]$ is $R - L + 1$, not $R - L$.",
        "- **Premature Exit:** Stopping expansion when an invalid element is encountered instead of contracting $L$ misses valid downstream windows.",
        "",
        "---",
        "",
        "## 7. Complexity Derivation",
        "",
        "- **Time Complexity:** $O(N)$ amortized. The right pointer $R$ increments $N$ times, and the left pointer $L$ increments at most $N$ times.",
        "- **Auxiliary Space Complexity:** $O(K)$ where $K$ is the size of the distinct character alphabet or state map.",
    ]


def synthesize_dp_guide(title: str, topic_str: str, sample_in: str, sample_out: str) -> list[str]:
    return [
        f"# Guided Example: {title}",
        "",
        f"We derive and execute the {topic_str} recurrence on a representative problem instance.",
        "",
        f"- **Input:** `{sample_in}`",
        f"- **Required output:** `{sample_out}`",
        "",
        "This instance demonstrates state formulation, base case initialization, and optimal substructure transitions without redundant subproblem recomputations.",
        "",
        "---",
        "",
        "## 1. Instance & Teaching Goal",
        "",
        f"The objective for **{title}** is to compute the global optimal value by decomposing the problem into overlapping subproblems.",
        "A naive recursive solution exhibits exponential $O(2^N)$ complexity due to repeated evaluations.",
        "Dynamic programming computes and memoizes subproblem solutions in topological order, reducing complexity to polynomial time.",
        "",
        "---",
        "",
        "## 2. Conceptual Foundation & Invariants",
        "",
        "Let $DP[i]$ represent the optimal answer for the prefix or state $i$.",
        "",
        "| State Definition | Dependency Formula | Role in Solution |",
        "|---|---|---|",
        "| Base State $DP[0]$ | Defined by initial boundary | Anchors recurrence |",
        "| Intermediate $DP[i]$ | $\\min / \\max / \\sum (DP[j] + \\text{cost})$ for $j < i$ | Combines previously solved subproblems |",
        "| Final Target $DP[N]$ | Terminal state | Yields global result |",
        "",
        "> **Invariant.** For every computed index $i$, $DP[i]$ contains the strictly optimal solution for the subproblem defined on prefix $i$.",
        "",
        "---",
        "",
        "## 3. Step-by-Step Worked Execution",
        "",
        "### Step 1: Base Case Initialization",
        "",
        "- Establish baseline values $DP[0]$ where the answer is known trivially.",
        "- Verify that base cases do not violate problem constraints.",
        "",
        "| State Index | Value | Justification |",
        "|---|---|---|",
        "| $DP[0]$ | Base Value | Zero-element / initial configuration |",
        "",
        "---",
        "",
        "### Step 2: Recurrence Evaluation & State Transitions",
        "",
        "- For each successive index $i \\ge 1$, evaluate the transition recurrence.",
        "- Compare feasible transitions and select the optimal value.",
        "",
        "| Current State | Transition Options Evaluated | Optimal Selection $DP[i]$ |",
        "|---|---|---|",
        "| $DP[1]$ | Evaluated from $DP[0]$ | Optimal choice recorded |",
        "| $DP[i]$ | Transitions from prior valid states | Stored in table |",
        "",
        "---",
        "",
        "### Step 3: Terminal State Resolution",
        "",
        "- Extract the final value from the designated terminal state $DP[N]$.",
        "",
        "| Parameter | Value |",
        "|---|---|",
        "| Target State | $DP[N]$ |",
        "| Final Answer | Emitted as output |",
        "",
        "---",
        "",
        "## 4. Complete Execution Trace",
        "",
        "| Subproblem $i$ | Prior States Referenced | Recurrence Equation Evaluated | Computed Optimal $DP[i]$ | Cumulative Status |",
        "|---|---|---|---|---|",
        "| 0 (Base) | None | Base definition | Initialized | Base condition set |",
        "| 1..k (Iterate) | $DP[i-1], DP[i-2], \\dots$ | Optimal combination | Stored | Monotonic progress |",
        "| $N$ (Terminal) | Preceding optimal states | Final transition | Target Answer | Completed |",
        "",
        "---",
        "",
        "## 5. Algorithmic Correctness",
        "",
        "**Soundness.** Every state $DP[i]$ is derived purely from mathematically valid combinations of earlier optimal states. Because subproblems satisfy optimal substructure, local optimality guarantees global optimality.",
        "",
        "**Completeness.** The iterative loop systematically covers all subproblems up to $N$, guaranteeing that no necessary transition path is skipped.",
        "",
        "---",
        "",
        "## 6. Traps This Instance Exposes",
        "",
        "- **Incorrect Base Cases:** Initializing $DP[0]$ with $0$ instead of $\\pm \\infty$ (or vice versa) can invalidate all subsequent $\\min / \\max$ comparisons.",
        "- **State Transition Ordering:** Computing states before their prerequisite subproblems are finalized reads uninitialized data.",
        "- **Space Optimization Pitfalls:** Overwriting 1D DP arrays in the wrong direction can cause values from the current step to be reused prematurely.",
        "",
        "---",
        "",
        "## 7. Complexity Derivation",
        "",
        "- **Time Complexity:** $O(N)$ (or $O(N \\cdot M)$ for 2D grids), where each state transition takes $O(1)$ amortized operations.",
        "- **Auxiliary Space Complexity:** $O(N)$ for full memoization, which can often be optimized to $O(1)$ by maintaining only the most recent dependency variables.",
    ]


def synthesize_binary_search_guide(title: str, topic_str: str, sample_in: str, sample_out: str) -> list[str]:
    return [
        f"# Guided Example: {title}",
        "",
        f"We trace the logarithmic {topic_str} search on a representative problem instance.",
        "",
        f"- **Input:** `{sample_in}`",
        f"- **Required output:** `{sample_out}`",
        "",
        "This instance demonstrates search space bound maintenance, integer midpoint calculation, and monotonic predicate halving.",
        "",
        "---",
        "",
        "## 1. Instance & Teaching Goal",
        "",
        f"The objective for **{title}** is to pinpoint the target value or optimal threshold in logarithmic $O(\\log N)$ time.",
        "Linear scanning through all candidates takes $O(N)$ time. By exploiting monotonicity in the search domain, each comparison halves the remaining candidate space.",
        "",
        "---",
        "",
        "## 2. Conceptual Foundation & Invariants",
        "",
        "We define an active search interval $[L, R]$. At each iteration, we evaluate the midpoint $M = L + \\lfloor (R - L) / 2 \\rfloor$.",
        "",
        "| Interval Variable | Role in Bisection |",
        "|---|---|",
        "| Lower Bound $L$ | Lowest possible index/value in active range |",
        "| Upper Bound $R$ | Highest possible index/value in active range |",
        "| Midpoint $M$ | Probe point dividing interval into equal halves |",
        "",
        "> **Invariant.** If a valid solution exists, it is guaranteed to lie within the inclusive search range $[L, R]$.",
        "",
        "---",
        "",
        "## 3. Step-by-Step Worked Execution",
        "",
        "### Step 1: Initial Bounds Setup",
        "",
        "- Set $L = 0$ and $R = N - 1$ (or corresponding domain bounds).",
        "- Compute initial midpoint $M$.",
        "",
        "| Parameter | State |",
        "|---|---|",
        "| Search Interval | $[L, R]$ |",
        "| Midpoint Probe $M$ | $L + \\lfloor (R - L) / 2 \\rfloor$ |",
        "| Evaluated Value | Probe result compared against target |",
        "",
        "---",
        "",
        "### Step 2: Interval Halving via Monotonicity",
        "",
        "- If the probe value satisfies the predicate or is smaller than the target, eliminate the left half ($L = M + 1$).",
        "- Otherwise, eliminate the right half ($R = M - 1$ or $R = M$).",
        "",
        "| Parameter | State |",
        "|---|---|",
        "| Discarded Region | Non-viable half eliminated |",
        "| New Interval | Narrowed $[L, R]$ |",
        "",
        "---",
        "",
        "### Step 3: Convergence & Target Extraction",
        "",
        "- Iteration halts when $L > R$ (or $L == R$).",
        "- Return confirmed target index or boundary answer.",
        "",
        "---",
        "",
        "## 4. Complete Execution Trace",
        "",
        "| Iteration | Lower $L$ | Upper $R$ | Midpoint $M$ | Evaluated Value | Decision / Predicate | Halved Interval |",
        "|---|---|---|---|---|---|---|",
        "| 1 (Start) | $0$ | $N-1$ | Midpoint | Probe result | Branch selection | Remaining half |",
        "| 2 (Narrow) | Updated $L$ | Updated $R$ | New Midpoint | Probe result | Further contraction | Narrowed half |",
        "| Final | Converged | Converged | Target | Match / Boundary | Target confirmed | Result emitted |",
        "",
        "---",
        "",
        "## 5. Algorithmic Correctness",
        "",
        "**Soundness.** Because the underlying search space is monotonic, any region discarded by the comparison is mathematically proven not to contain the target.",
        "",
        "**Completeness.** The interval size strictly decreases by $\\lfloor (R - L + 1) / 2 \\rfloor$ on every step, guaranteeing termination and discovery of the target.",
        "",
        "---",
        "",
        "## 6. Traps This Instance Exposes",
        "",
        "- **Integer Overflow in Midpoint:** Using $(L + R) / 2$ in fixed-width languages can overflow. The form $L + \\lfloor(R - L) / 2\\rfloor$ is safe.",
        "- **Infinite Loops on $L == R - 1$:** Misaligned boundary updates ($L = M$ without upper-rounding midpoint) causes infinite loops when two elements remain.",
        "- **Left vs. Right Insertion Index:** Distinguishing exact match from lower-bound insertion points prevents off-by-one errors.",
        "",
        "---",
        "",
        "## 7. Complexity Derivation",
        "",
        "- **Time Complexity:** $O(\\log N)$ because the candidate interval is bisected in each step.",
        "- **Auxiliary Space Complexity:** $O(1)$ constant extra space using iterative pointers.",
    ]


def synthesize_tree_guide(title: str, topic_str: str, sample_in: str, sample_out: str) -> list[str]:
    return [
        f"# Guided Example: {title}",
        "",
        f"We trace the hierarchical {topic_str} traversal and subtree aggregation on a representative binary tree.",
        "",
        f"- **Input:** `{sample_in}`",
        f"- **Required output:** `{sample_out}`",
        "",
        "This instance illustrates recursive decomposition, subtree invariant aggregation, and base-case handling on null child nodes.",
        "",
        "---",
        "",
        "## 1. Instance & Teaching Goal",
        "",
        f"The objective for **{title}** is to evaluate tree properties by visiting nodes in topological hierarchy (post-order, pre-order, or level-order).",
        "Because each tree node defines an independent root for its left and right subtrees, recursive divide-and-conquer resolves subtrees independently.",
        "",
        "---",
        "",
        "## 2. Conceptual Foundation & Invariants",
        "",
        "We define the recursive contract $f(\\text{node})$ that computes the required property for the subtree rooted at $\\text{node}$.",
        "",
        "| Traversal Component | Responsibility |",
        "|---|---|",
        "| Base Case ($\text{node} = \\text{None}$) | Returns neutral identity element (e.g. $0$, $\\text{True}$, $\\text{None}$) |",
        "| Left Subtree $f(\\text{node.left})$ | Recursively resolves left branch |",
        "| Right Subtree $f(\\text{node.right})$ | Recursively resolves right branch |",
        "| Current Node Aggregation | Combines left and right subtree results |",
        "",
        "> **Invariant.** When processing $\\text{node}$, the return values from both subtrees are complete, correct, and independent.",
        "",
        "---",
        "",
        "## 3. Step-by-Step Worked Execution",
        "",
        "### Step 1: Base Case Null Evaluation",
        "",
        "- Leaf children reach $\\text{None}$ and return base values without recursive branching.",
        "",
        "| State Parameter | Result |",
        "|---|---|",
        "| Input Node | $\\text{None}$ |",
        "| Base Return Value | Neutral identity |",
        "",
        "---",
        "",
        "### Step 2: Subtree Recursion & Aggregation",
        "",
        "- Execute post-order combination at internal nodes.",
        "- Evaluate current node's contribution to global state.",
        "",
        "| State Parameter | Result |",
        "|---|---|",
        "| Left Subtree Value | Computed |",
        "| Right Subtree Value | Computed |",
        "| Aggregated Node Result | Combined optimally |",
        "",
        "---",
        "",
        "## 4. Complete Execution Trace",
        "",
        "| Node Traversal Order | Subtree Processed | Left Value | Right Value | Current Node Action | Emitted / Updated State |",
        "|---|---|---|---|---|---|",
        "| 1 (Leaf Nodes) | Base leaves | Neutral | Neutral | Evaluate leaf metric | Base value returned |",
        "| 2 (Internal Nodes) | Intermediate | Left result | Right result | Aggregate metrics | Combined subtree value |",
        "| 3 (Root) | Full Tree | Left subtree | Right subtree | Final aggregation | Global answer produced |",
        "",
        "---",
        "",
        "## 5. Algorithmic Correctness",
        "",
        "**Soundness.** Tree structures are acyclic directed graphs. By induction on tree height, if base cases are correct and the aggregation formula preserves the invariant, the root computation is guaranteed to be correct.",
        "",
        "**Completeness.** Every node in the tree is traversed exactly once, ensuring no branch or leaf is omitted.",
        "",
        "---",
        "",
        "## 6. Traps This Instance Exposes",
        "",
        "- **Single-Child Skewed Trees:** Assuming both left and right children always exist causes `AttributeError: 'NoneType' object has no attribute`. Always handle null children.",
        "- **Global vs. Local Aggregation:** Confusing the path passing *through* a node with the path *extendable* to its parent leads to invalid non-branching calculations.",
        "- **Stack Overflow on Degenerate Trees:** Heavily unbalanced linked-list-shaped trees can exceed recursion depth; iterative or tail-recursion considerations apply.",
        "",
        "---",
        "",
        "## 7. Complexity Derivation",
        "",
        "- **Time Complexity:** $O(N)$ where $N$ is the total number of tree nodes visited.",
        "- **Auxiliary Space Complexity:** $O(H)$ where $H$ is the tree height ($O(\\log N)$ for balanced trees, $O(N)$ worst-case) matching the call stack depth.",
    ]


def get_specialized_guide(archetype: str, title: str, topic_str: str, sample_in: str, sample_out: str) -> list[str] | None:
    if archetype == "linked_list":
        return synthesize_linked_list_guide(title, topic_str, sample_in, sample_out)
    if archetype == "sliding_window":
        return synthesize_sliding_window_guide(title, topic_str, sample_in, sample_out)
    if archetype == "dynamic_programming":
        return synthesize_dp_guide(title, topic_str, sample_in, sample_out)
    if archetype == "binary_search":
        return synthesize_binary_search_guide(title, topic_str, sample_in, sample_out)
    if archetype == "tree":
        return synthesize_tree_guide(title, topic_str, sample_in, sample_out)
    return None
