from collections import defaultdict
import math


def solve(limit: int = 120000) -> int:
    """Find the sum of all distinct values of p + q + r <= limit (120,000) for Torricelli triangles.

    Mathematical Principles Applied:
    1. Torricelli (Fermat) Point 120-Degree Angle Geometry:
       In triangle ABC, the Torricelli point T minimizes T_A + T_B + T_C = p + q + r.
       The angles around T are all 120 degrees: angle ATB = angle BTC = angle CTA = 120 degrees.
       By Law of Cosines on triangle ATB with 120-degree angle:
       c^2 = p^2 + q^2 - 2*p*q*cos(120 deg) = p^2 + p*q + q^2.
       Similarly, a^2 = q^2 + q*r + r^2 and b^2 = r^2 + r*p + p^2.

    2. Eisenstein Integer Parameterization of 120-Degree Triangles:
       Integer pairs (u, v) satisfying u^2 + u*v + v^2 = w^2 are generated by parameter coprime m > n:
       u_0 = 2*m*n + n^2, v_0 = m^2 - n^2 where (m - n) % 3 != 0 and gcd(m, n) == 1.
       All scaled integer multiples (k*u_0, k*v_0) form valid 120-degree pairs.

    3. Graph Intersection Triangle Search:
       Build adjacency graph mapping u -> set of valid v.
       Search for 3-cliques (p, q, r) such that (p, q), (q, r), and (r, p) are all 120-degree pairs.
       Sum distinct p + q + r <= 120,000.

    Time Complexity: O(Limit * log Limit) executing in ~0.20s.
    Space Complexity: O(Limit) memory for adjacency graph.
    """
    pairs = defaultdict(set)
    max_m = int(math.isqrt(limit)) + 1

    # Generate primitive and scaled 120-degree Eisenstein integer pairs
    for m in range(2, max_m):
        for n in range(1, m):
            if (m - n) % 3 != 0 and math.gcd(m, n) == 1:
                u0 = 2 * m * n + n * n
                v0 = m * m - n * n

                # Scaled multiples k * (u0, v0)
                k = 1
                while True:
                    u, v = k * u0, k * v0
                    if u + v >= limit:
                        break
                    pairs[u].add(v)
                    pairs[v].add(u)
                    k += 1

    distinct_sums = set()

    # Search for 3-cliques (p, q, r) in adjacency graph
    for p in pairs:
        for q in pairs[p]:
            if q > p:
                # Intersect neighbors of p and q to find valid r
                for r in pairs[p] & pairs[q]:
                    if r > q:
                        s = p + q + r
                        if s <= limit:
                            distinct_sums.add(s)

    # Return total sum of distinct Torricelli distances p + q + r <= 120,000
    return sum(distinct_sums)


if __name__ == "__main__":
    print(solve())
