# Optimal solution generated by LLM (doocs/leetcode source unavailable).
from math import gcd


class Solution:
    def minimumTime(self, d: list[int], r: list[int]) -> int:
        def required_hours(deliveries: int, recharge_interval: int) -> int:
            return deliveries + (deliveries - 1) // (recharge_interval - 1)

        common_recharge_period = r[0] // gcd(r[0], r[1]) * r[1]
        return max(
            required_hours(d[0], r[0]),
            required_hours(d[1], r[1]),
            required_hours(d[0] + d[1], common_recharge_period),
        )
