# Optimal solution generated by AI (doocs/leetcode source unavailable).
from math import lcm
from typing import List


class Solution:
    def minimumIncrements(self, nums: List[int], target: List[int]) -> int:
        target_count = len(target)
        full_mask = (1 << target_count) - 1
        subset_lcm = [1] * (full_mask + 1)
        for mask in range(1, full_mask + 1):
            bit = mask & -mask
            index = bit.bit_length() - 1
            subset_lcm[mask] = lcm(subset_lcm[mask ^ bit], target[index])

        infinity = 10**30
        dp = [infinity] * (full_mask + 1)
        dp[0] = 0

        for value in nums:
            next_dp = dp.copy()
            for covered, current_cost in enumerate(dp):
                if current_cost == infinity:
                    continue
                remaining = full_mask ^ covered
                subset = remaining
                while subset:
                    multiple = subset_lcm[subset]
                    increment = (-value) % multiple
                    next_mask = covered | subset
                    next_dp[next_mask] = min(next_dp[next_mask], current_cost + increment)
                    subset = (subset - 1) & remaining
            dp = next_dp

        return dp[full_mask]
