# Optimal solution generated by LLM (doocs/leetcode source unavailable).
class Solution:
    def goodSubtreeSum(self, vals: List[int], par: List[int]) -> int:
        full = (1 << 10) - 1
        mod = 1_000_000_007
        n = len(vals)

        def digit_mask(value: int) -> int:
            mask = 0
            while value:
                bit = 1 << (value % 10)
                if mask & bit:
                    return -1
                mask |= bit
                value //= 10
            return mask

        children = [[] for _ in range(n)]
        for node in range(1, n):
            children[par[node]].append(node)

        order = [0]
        for node in order:
            order.extend(children[node])

        states = [None] * n
        total = 0
        for node in reversed(order):
            dp = [-1] * 1024
            dp[0] = 0
            mask = digit_mask(vals[node])
            if mask >= 0:
                dp[mask] = vals[node]

            for child_node in children[node]:
                child = states[child_node]
                merged = [-1] * 1024
                left_masks = [mask for mask, score in enumerate(dp) if score >= 0]
                right_masks = [mask for mask, score in enumerate(child) if score >= 0]
                submask_cost = sum(1 << (10 - mask.bit_count()) for mask in left_masks)
                if len(left_masks) * len(right_masks) <= submask_cost:
                    for left_mask in left_masks:
                        for right_mask in right_masks:
                            if left_mask & right_mask == 0:
                                combined = left_mask | right_mask
                                merged[combined] = max(
                                    merged[combined],
                                    dp[left_mask] + child[right_mask],
                                )
                else:
                    for left_mask in left_masks:
                        available = full ^ left_mask
                        right_mask = available
                        while True:
                            if child[right_mask] >= 0:
                                combined = left_mask | right_mask
                                merged[combined] = max(
                                    merged[combined],
                                    dp[left_mask] + child[right_mask],
                                )
                            if right_mask == 0:
                                break
                            right_mask = (right_mask - 1) & available
                dp = merged

            states[node] = dp
            total += max(dp)

        return total % mod
