"""Project Euler Problem 610: Roman Numerals II.

Find the expected value of the random Roman numeral generated by the process,
rounded to 8 decimal places.
"""

from fractions import Fraction
from typing import Dict, List, Tuple

_ROMAN_MINIMAL_TABLE: List[Tuple[int, str]] = [
    (1000, "M"),
    (900, "CM"),
    (500, "D"),
    (400, "CD"),
    (100, "C"),
    (90, "XC"),
    (50, "L"),
    (40, "XL"),
    (10, "X"),
    (9, "IX"),
    (5, "V"),
    (4, "IV"),
    (1, "I"),
]

_LETTERS = "IVXLCDM"
_P_STOP = Fraction(1, 50)
_P_LETTER = Fraction(7, 50)


def _to_min_roman(n: int) -> str:
    if n <= 0:
        return ""
    out: List[str] = []
    for value, token in _ROMAN_MINIMAL_TABLE:
        while n >= value:
            out.append(token)
            n -= value
    return "".join(out)


def _round_fraction(fr: Fraction, digits: int) -> str:
    scale = 10**digits
    scaled_num = fr.numerator * scale
    q, r = divmod(scaled_num, fr.denominator)
    if 2 * r >= fr.denominator:
        q += 1
    int_part, frac_part = divmod(q, scale)
    return f"{int_part}.{frac_part:0{digits}d}"


def solve() -> str:
    """Compute the expected value of the randomly generated minimal Roman numeral."""
    roman_to_val: Dict[str, int] = {}
    romans: List[str] = []
    for n in range(1, 1000):
        r = _to_min_roman(n)
        roman_to_val[r] = n
        romans.append(r)

    roman_set = set(romans)
    romans.sort(key=len, reverse=True)

    expected_map: Dict[str, Fraction] = {}
    for r in romans:
        v = roman_to_val[r]
        extensions = [r + ch for ch in _LETTERS if (r + ch) in roman_set]
        denom = _P_STOP + _P_LETTER * len(extensions)
        numer = _P_STOP * v
        for ext in extensions:
            numer += _P_LETTER * expected_map[ext]
        expected_map[r] = numer / denom

    sum_initial = (
        expected_map["I"]
        + expected_map["V"]
        + expected_map["X"]
        + expected_map["L"]
        + expected_map["C"]
        + expected_map["D"]
    )
    b_val = (_P_LETTER * (1000 + sum_initial)) / (1 - _P_LETTER)
    return _round_fraction(b_val, 8)


if __name__ == "__main__":
    print(solve())
