# Optimal solution generated by AI (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def minPartitionScore(self, nums: List[int], k: int) -> int:
        n = len(nums)
        total = sum(nums)
        slopes = [0] * (n + 1)
        intercepts = [0] * (n + 1)
        counts = [0] * (n + 1)

        def run(penalty: int) -> tuple[int, int]:
            head = tail = 0
            slopes[0] = intercepts[0] = counts[0] = 0
            prefix = 0
            cost = parts = 0

            for number in nums:
                prefix += number

                while head < tail:
                    first = slopes[head] * prefix + intercepts[head]
                    second = slopes[head + 1] * prefix + intercepts[head + 1]
                    if second < first or (second == first and counts[head + 1] > counts[head]):
                        head += 1
                    else:
                        break

                cost = prefix * prefix + prefix + slopes[head] * prefix + intercepts[head] + penalty
                parts = counts[head] + 1
                new_slope = -2 * prefix
                new_intercept = cost + prefix * prefix - prefix

                while head < tail:
                    left = (intercepts[tail] - intercepts[tail - 1]) * (slopes[tail] - new_slope)
                    right = (new_intercept - intercepts[tail]) * (slopes[tail - 1] - slopes[tail])
                    if left <= right:
                        break
                    tail -= 1

                tail += 1
                slopes[tail] = new_slope
                intercepts[tail] = new_intercept
                counts[tail] = parts

            return cost, parts

        low, high = 0, total * total
        while low < high:
            middle = (low + high + 1) // 2
            _, parts = run(middle)
            if parts >= k:
                low = middle
            else:
                high = middle - 1

        penalized_cost, _ = run(low)
        return (penalized_cost - low * k) // 2
