def solve(rows: int = 1000) -> int:
    """Find smallest sub-triangle sum in 1000-row triangular array generated by LCG.
    
    Time Complexity: O(rows^3)
    Space Complexity: O(rows^2)
    """
    total_elements = rows * (rows + 1) // 2

    # 1. Linear Congruential Generator
    t = 0
    s = [0] * (total_elements + 1)
    mod = 2**20
    half_mod = 2**19
    for k in range(1, total_elements + 1):
        t = (615949 * t + 797807) % mod
        s[k] = t - half_mod

    # 2. Build row prefix sums
    row_pref = []
    idx = 1
    for r in range(rows):
        pref = [0] * (r + 2)
        for c in range(r + 1):
            pref[c + 1] = pref[c] + s[idx]
            idx += 1
        row_pref.append(pref)

    # 3. Search all sub-triangles for minimum sum
    min_sum = 0
    for r in range(rows):
        for c in range(r + 1):
            curr_sum = 0
            for depth in range(rows - r):
                curr_sum += row_pref[r + depth][c + depth + 1] - row_pref[r + depth][c]
                if curr_sum < min_sum:
                    min_sum = curr_sum

    return min_sum
