# Optimal solution generated by AI (doocs/leetcode source unavailable).
class Solution:
    def kthRemainingInteger(self, nums: list[int], queries: list[list[int]]) -> list[int]:
        even_ranks = []
        even_prefix = [0]
        for value in nums:
            if value % 2 == 0:
                even_ranks.append(value // 2)
            even_prefix.append(len(even_ranks))

        answer = []
        for left, right, k in queries:
            even_left = even_prefix[left]
            even_right = even_prefix[right + 1]

            low = even_left
            high = even_right
            while low < high:
                middle = (low + high) // 2
                removed_before = middle - even_left
                missing_before = even_ranks[middle] - 1 - removed_before
                if missing_before >= k:
                    high = middle
                else:
                    low = middle + 1

            answer.append(2 * (k + low - even_left))

        return answer
