# Optimal solution generated by AI (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def timeTaken(self, edges: List[List[int]]) -> List[int]:
        node_count = len(edges) + 1
        graph = [[] for _ in range(node_count)]
        for first, second in edges:
            graph[first].append(second)
            graph[second].append(first)

        parent = [-1] * node_count
        order = [0]
        for node in order:
            for neighbor in graph[node]:
                if neighbor == parent[node]:
                    continue
                parent[neighbor] = node
                order.append(neighbor)

        downward = [0] * node_count
        for node in reversed(order):
            for neighbor in graph[node]:
                if parent[neighbor] == node:
                    contribution = downward[neighbor] + (1 if neighbor % 2 else 2)
                    downward[node] = max(downward[node], contribution)

        upward = [0] * node_count
        answer = [0] * node_count

        for node in order:
            best = upward[node]
            second_best = 0
            best_child = -1

            for neighbor in graph[node]:
                if parent[neighbor] != node:
                    continue
                contribution = downward[neighbor] + (1 if neighbor % 2 else 2)
                if contribution > best:
                    second_best = best
                    best = contribution
                    best_child = neighbor
                elif contribution > second_best:
                    second_best = contribution

            answer[node] = best
            enter_node_cost = 1 if node % 2 else 2

            for neighbor in graph[node]:
                if parent[neighbor] == node:
                    outside = second_best if neighbor == best_child else best
                    upward[neighbor] = enter_node_cost + outside

        return answer
