# Optimal solution generated by AI (doocs/leetcode source unavailable).
MODULO = 1_000_000_007


class Solution:
    def maxTotalValue(self, value: list[int], decay: list[int], m: int) -> int:
        selections = 0
        for initial, step in zip(value, decay):
            selections += (initial - 1) // step + 1
            if selections >= m:
                selections = m
                break

        low = 1
        high = max(value)
        while low < high:
            threshold = (low + high + 1) // 2
            count = 0
            for initial, step in zip(value, decay):
                if initial >= threshold:
                    count += (initial - threshold) // step + 1
                    if count >= selections:
                        break

            if count >= selections:
                low = threshold
            else:
                high = threshold - 1

        threshold = low
        total = 0
        count = 0
        for initial, step in zip(value, decay):
            if initial < threshold:
                continue

            terms = (initial - threshold) // step + 1
            last = initial - (terms - 1) * step
            total += terms * (initial + last) // 2
            count += terms

        total -= (count - selections) * threshold
        return total % MODULO
