# Optimal solution generated by AI (doocs/leetcode source unavailable).
from heapq import heappop, heappush


class Solution:
    def minTime(self, n: int, k: int, m: int, time: List[int], mul: List[float]) -> float:
        if k == 1 and n > 1:
            return -1.0

        full_mask = (1 << n) - 1
        maximum_time = [0] * (1 << n)

        for mask in range(1, 1 << n):
            lowest_bit = mask & -mask
            person = lowest_bit.bit_length() - 1
            maximum_time[mask] = max(
                maximum_time[mask ^ lowest_bit],
                time[person],
            )

        distances = [[float("inf")] * m for _ in range(1 << n)]
        distances[full_mask][0] = 0.0
        queue = [(0.0, full_mask, 0)]

        while queue:
            elapsed, mask, stage = heappop(queue)

            if elapsed != distances[mask][stage]:
                continue

            if mask == 0:
                return elapsed

            group = mask

            while group:
                if group.bit_count() <= k:
                    crossing_time = maximum_time[group] * mul[stage]
                    next_stage = (stage + int(crossing_time + 1e-9)) % m
                    remaining = mask ^ group
                    arrival_time = elapsed + crossing_time

                    if remaining == 0:
                        if arrival_time < distances[0][next_stage]:
                            distances[0][next_stage] = arrival_time
                            heappush(queue, (arrival_time, 0, next_stage))
                    else:
                        returners = full_mask ^ remaining

                        while returners:
                            returner_bit = returners & -returners
                            person = returner_bit.bit_length() - 1
                            return_time = time[person] * mul[next_stage]
                            final_stage = (next_stage + int(return_time + 1e-9)) % m
                            next_mask = remaining | returner_bit
                            total_time = arrival_time + return_time

                            if total_time < distances[next_mask][final_stage]:
                                distances[next_mask][final_stage] = total_time
                                heappush(
                                    queue,
                                    (total_time, next_mask, final_stage),
                                )

                            returners ^= returner_bit

                group = (group - 1) & mask

        return -1.0
