"""Project Euler Problem 507: Shortest Lattice Vector.

Find sum_{n=1..20000000} S(n), where S(n) is the minimum L1 Manhattan norm
of non-zero vectors in the 2D lattice spanned by V_n and W_n generated by Tribonacci residues.
"""

from typing import Tuple

MOD = 10_000_000


def _best_reduction(
    a1: int, a2: int, a3: int, b1: int, b2: int, b3: int, nb: int
) -> Tuple[int, int]:
    best_m = 0
    best_v = nb

    if a1:
        q = b1 // a1
        v = abs(b1 - q * a1) + abs(b2 - q * a2) + abs(b3 - q * a3)
        if v < best_v:
            best_v = v
            best_m = q
        q += 1
        v = abs(b1 - q * a1) + abs(b2 - q * a2) + abs(b3 - q * a3)
        if v < best_v:
            best_v = v
            best_m = q

    if a2:
        q = b2 // a2
        v = abs(b1 - q * a1) + abs(b2 - q * a2) + abs(b3 - q * a3)
        if v < best_v:
            best_v = v
            best_m = q
        q += 1
        v = abs(b1 - q * a1) + abs(b2 - q * a2) + abs(b3 - q * a3)
        if v < best_v:
            best_v = v
            best_m = q

    if a3:
        q = b3 // a3
        v = abs(b1 - q * a1) + abs(b2 - q * a2) + abs(b3 - q * a3)
        if v < best_v:
            best_v = v
            best_m = q
        q += 1
        v = abs(b1 - q * a1) + abs(b2 - q * a2) + abs(b3 - q * a3)
        if v < best_v:
            best_v = v
            best_m = q

    return best_m, best_v


def _shortest_l1(
    v1: int, v2: int, v3: int, w1: int, w2: int, w3: int
) -> int:
    a1, a2, a3 = v1, v2, v3
    b1, b2, b3 = w1, w2, w3

    if (a1 | a2 | a3) == 0:
        return abs(b1) + abs(b2) + abs(b3)
    if (b1 | b2 | b3) == 0:
        return abs(a1) + abs(a2) + abs(a3)

    while True:
        na = abs(a1) + abs(a2) + abs(a3)
        nb = abs(b1) + abs(b2) + abs(b3)

        if nb < na:
            a1, a2, a3, b1, b2, b3 = b1, b2, b3, a1, a2, a3
            na, nb = nb, na

        m, reduced = _best_reduction(a1, a2, a3, b1, b2, b3, nb)
        if reduced >= nb:
            break

        b1 -= m * a1
        b2 -= m * a2
        b3 -= m * a3

    s = abs(a1) + abs(a2) + abs(a3)
    t = abs(b1) + abs(b2) + abs(b3)
    if t and t < s:
        s = t

    return s


def solve(limit: int = 20_000_000) -> int:
    """Compute sum_{n=1..limit} S(n) using Tribonacci streaming and 2D L1 lattice reduction."""
    prev2, prev1, cur = 1, 0, 0
    total = 0

    for _ in range(limit):
        r = [0] * 12
        for j in range(12):
            r[j] = cur
            nxt = prev2 + prev1 + cur
            if nxt >= MOD:
                nxt -= MOD
                if nxt >= MOD:
                    nxt -= MOD
            prev2, prev1, cur = prev1, cur, nxt

        v1 = r[0] - r[1]
        v2 = r[2] + r[3]
        v3 = r[4] * r[5]

        w1 = r[6] - r[7]
        w2 = r[8] + r[9]
        w3 = r[10] * r[11]

        total += _shortest_l1(v1, v2, v3, w1, w2, w3)

    return total


if __name__ == "__main__":
    print(solve())
