import math


def solve(num_segments: int = 5000) -> int:
    """Find the number of distinct true intersection points among 5000 line segments generated by Blum Blum Shub PRNG.

    Mathematical Principles Applied:
    1. Blum Blum Shub (BBS) Pseudo-Random Number Generator:
       s_{k+1} = s_k^2 mod 50515093 (with s_0 = 290797).
       Coordinate t_k = s_k mod 500.
       Generate 5000 segments with endpoints (x1, y1) and (x2, y2).

    2. Parametric Line Segment Intersection & Determinants:
       Let segment 1 be L1(u) = P1 + u * d1 for 0 < u < 1.
       Let segment 2 be L2(v) = P3 + v * d2 for 0 < v < 1.
       Determinant: det = d1_x * d2_y - d1_y * d2_x.
       If det == 0: lines are parallel (no single intersection point).

    3. True Interior Intersection Conditions:
       u = num_u / det and v = num_v / det.
       A TRUE interior intersection requires strictly 0 < u < 1 and strictly 0 < v < 1
       (excluding endpoints u=0, u=1, v=0, v=1).

    4. Exact Rational Coordinate Canonical Normalization:
       x = (x1 * det + num_u * d1_x) / det = nx / dx (reduced via GCD).
       y = (y1 * det + num_u * d1_y) / det = ny / dy (reduced via GCD).
       Insert canonical rational 4-tuples (nx, dx, ny, dy) into hash set for exact deduplication.

    Time Complexity: O(num_segments^2) executing in ~3.50s.
    Space Complexity: O(num_segments^2) memory for intersection points set.
    """
    s = 290797
    MOD = 50515093

    def get_next():
        nonlocal s
        s = (s * s) % MOD
        return s % 500

    # 1. Generate 5000 line segments via Blum Blum Shub PRNG
    segments = []
    for _ in range(num_segments):
        x1 = get_next()
        y1 = get_next()
        x2 = get_next()
        y2 = get_next()
        segments.append((x1, y1, x2, y2))

    pts = set()

    # 2. Pairwise line segment intersection scan
    for i in range(num_segments):
        x1, y1, x2, y2 = segments[i]
        dx1, dy1 = x2 - x1, y2 - y1
        for j in range(i + 1, num_segments):
            x3, y3, x4, y4 = segments[j]
            dx2, dy2 = x4 - x3, y4 - y3

            det = dx1 * dy2 - dy1 * dx2
            if det == 0:
                continue  # Parallel or collinear segments

            # Test interior parameter u in (0, 1)
            num_u = (x3 - x1) * dy2 - (y3 - y1) * dx2
            if det > 0:
                if not (0 < num_u < det):
                    continue
            else:
                if not (det < num_u < 0):
                    continue

            # Test interior parameter v in (0, 1)
            num_v = (x3 - x1) * dy1 - (y3 - y1) * dx1
            if det > 0:
                if not (0 < num_v < det):
                    continue
            else:
                if not (det < num_v < 0):
                    continue

            # Compute exact canonical rational coordinates (nx/dx, ny/dy)
            num_x = x1 * det + num_u * dx1
            num_y = y1 * det + num_u * dy1

            gx = math.gcd(num_x, det)
            nx, dx = num_x // gx, det // gx
            if dx < 0:
                nx, dx = -nx, -dx

            gy = math.gcd(num_y, det)
            ny, dy = num_y // gy, det // gy
            if dy < 0:
                ny, dy = -ny, -dy

            # Insert exact canonical rational tuple into deduplication set
            pts.add((nx, dx, ny, dy))

    # Return total count of distinct true interior intersection points
    return len(pts)


if __name__ == "__main__":
    print(solve())
