# Optimal solution generated by AI (doocs/leetcode source unavailable).
from math import comb


class Solution:
    def popcountDepth(self, n: int, k: int) -> int:
        if k == 0:
            return 1

        bit_count = n.bit_length()
        depth = [0] * (bit_count + 1)
        for value in range(2, bit_count + 1):
            depth[value] = 1 + depth[value.bit_count()]

        def count_with_ones(ones: int) -> int:
            total = 0
            remaining = ones

            for bit in range(bit_count - 1, -1, -1):
                if (n >> bit) & 1:
                    if remaining <= bit:
                        total += comb(bit, remaining)
                    remaining -= 1
                    if remaining < 0:
                        break
            else:
                if remaining == 0:
                    total += 1

            return total

        answer = sum(count_with_ones(ones) for ones in range(1, bit_count + 1) if depth[ones] == k - 1)

        if k == 1:
            answer -= 1
        return answer
