# Optimal solution generated by LLM (doocs/leetcode source unavailable).
from bisect import bisect_left
from typing import List


class Solution:
    def minInversionCount(self, nums: List[int], k: int) -> int:
        values = sorted(set(nums))
        tree = [0] * (len(values) + 1)

        def rank(value: int) -> int:
            return bisect_left(values, value) + 1

        def add(index: int, delta: int) -> None:
            while index < len(tree):
                tree[index] += delta
                index += index & -index

        def prefix_sum(index: int) -> int:
            total = 0
            while index:
                total += tree[index]
                index -= index & -index
            return total

        inversions = 0
        for index in range(k):
            compressed = rank(nums[index])
            inversions += index - prefix_sum(compressed)
            add(compressed, 1)

        answer = inversions
        for right in range(k, len(nums)):
            outgoing = rank(nums[right - k])
            inversions -= prefix_sum(outgoing - 1)
            add(outgoing, -1)

            incoming = rank(nums[right])
            inversions += (k - 1) - prefix_sum(incoming)
            add(incoming, 1)
            answer = min(answer, inversions)

        return answer
