# Optimal solution generated by AI (doocs/leetcode source unavailable).
class Solution:
    def subtreeInversionSum(self, edges: List[List[int]], nums: List[int], k: int) -> int:
        n = len(nums)
        graph = [[] for _ in range(n)]
        for first, second in edges:
            graph[first].append(second)
            graph[second].append(first)

        parent = [-2] * n
        parent[0] = -1
        order = [0]
        for node in order:
            for neighbor in graph[node]:
                if neighbor != parent[node]:
                    parent[neighbor] = node
                    order.append(neighbor)

        even = [None] * n
        odd = [None] * n

        for node in reversed(order):
            keep_even = [nums[node]] * (k + 1)
            keep_odd = [-nums[node]] * (k + 1)
            invert_even = -nums[node]
            invert_odd = nums[node]

            for child in graph[node]:
                if parent[child] != node:
                    continue
                child_even = even[child]
                child_odd = odd[child]

                for distance in range(k):
                    keep_even[distance] += child_even[distance + 1]
                    keep_odd[distance] += child_odd[distance + 1]
                keep_even[k] += child_even[k]
                keep_odd[k] += child_odd[k]
                invert_even += child_odd[1]
                invert_odd += child_even[1]

                even[child] = None
                odd[child] = None

            keep_even[k] = max(keep_even[k], invert_even)
            keep_odd[k] = max(keep_odd[k], invert_odd)
            even[node] = keep_even
            odd[node] = keep_odd

        return even[0][k]
