# Optimal solution generated by AI (doocs/leetcode source unavailable).
class Solution:
    def countArrays(self, original: List[int], bounds: List[List[int]]) -> int:
        lower, upper = bounds[0]
        base = original[0]
        for index in range(1, len(original)):
            offset = original[index] - base
            lower = max(lower, bounds[index][0] - offset)
            upper = min(upper, bounds[index][1] - offset)
        return max(0, upper - lower + 1)
