# Optimal solution generated by AI (doocs/leetcode source unavailable).
class Solution:
    def maxConsistentColumns(self, grid: List[List[int]], limit: int) -> int:
        rows = len(grid)
        columns = len(grid[0])
        dp = [1] * columns
        answer = 1

        for right in range(columns):
            for left in range(right):
                for row in range(rows):
                    if abs(grid[row][right] - grid[row][left]) > limit:
                        break
                else:
                    dp[right] = max(dp[right], dp[left] + 1)
            answer = max(answer, dp[right])

        return answer
