# Optimal solution generated by AI (doocs/leetcode source unavailable).
from collections import Counter
from math import isqrt


class Solution:
    def numberOfPairs(
        self,
        nums1: list[int],
        nums2: list[int],
        queries: list[list[int]],
    ) -> list[int]:
        fixed_frequencies = Counter(nums1)
        fixed_items = list(fixed_frequencies.items())
        length = len(nums2)
        block_size = isqrt((length * len(fixed_items) + 1) // 2) + 1
        block_count = (length + block_size - 1) // block_size
        lazy = [0] * block_count
        block_frequencies = [
            Counter(nums2[start : min(start + block_size, length)]) for start in range(0, length, block_size)
        ]

        def update_boundary(block: int, left: int, right: int, delta: int) -> None:
            start = block * block_size
            end = min(start + block_size, length)
            offset = lazy[block]
            if offset:
                for index in range(start, end):
                    nums2[index] += offset
                lazy[block] = 0

            for index in range(left, right + 1):
                nums2[index] += delta
            block_frequencies[block] = Counter(nums2[start:end])

        answer = []
        for query in queries:
            if query[0] == 1:
                _, left, right, delta = query
                left_block = left // block_size
                right_block = right // block_size
                if left_block == right_block:
                    update_boundary(left_block, left, right, delta)
                    continue

                update_boundary(
                    left_block,
                    left,
                    (left_block + 1) * block_size - 1,
                    delta,
                )
                update_boundary(
                    right_block,
                    right_block * block_size,
                    right,
                    delta,
                )
                for block in range(left_block + 1, right_block):
                    lazy[block] += delta
                continue

            target = query[1]
            pair_count = 0
            for block, frequencies in enumerate(block_frequencies):
                adjusted_target = target - lazy[block]
                for value, multiplicity in fixed_items:
                    pair_count += multiplicity * frequencies.get(
                        adjusted_target - value,
                        0,
                    )
            answer.append(pair_count)

        return answer
