# Optimal solution generated by AI (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def maximumSaleItems(self, items: List[List[int]], budget: int) -> int:
        n = len(items)
        factor_frequencies = [0] * (n + 1)
        minimum_price = min(price for _, price in items)
        for factor, _ in items:
            factor_frequencies[factor] += 1

        divisible_counts = [0] * (n + 1)
        for factor in range(1, n + 1):
            for multiple in range(factor, n + 1, factor):
                divisible_counts[factor] += factor_frequencies[multiple]

        boosted_batches = sorted((price, divisible_counts[factor] - 1) for factor, price in items)

        answer = 0
        remaining = budget
        for price, boosted_copies in boosted_batches:
            if price > 2 * minimum_price or price > remaining:
                break

            bought = min(boosted_copies, remaining // price)
            answer += 2 * bought
            remaining -= price * bought
            if bought < boosted_copies:
                break

        return answer + remaining // minimum_price
