# Optimal solution generated by AI (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def minCost(self, n: int, cost: List[List[int]]) -> int:
        inf = float("inf")
        dp = [[inf] * 3 for _ in range(3)]
        for left_color in range(3):
            for right_color in range(3):
                if left_color != right_color:
                    dp[left_color][right_color] = cost[0][left_color] + cost[n - 1][right_color]

        for left in range(1, n // 2):
            right = n - 1 - left
            next_dp = [[inf] * 3 for _ in range(3)]
            for previous_left in range(3):
                for previous_right in range(3):
                    current = dp[previous_left][previous_right]
                    for left_color in range(3):
                        if left_color == previous_left:
                            continue
                        for right_color in range(3):
                            if right_color == previous_right or right_color == left_color:
                                continue
                            candidate = current + cost[left][left_color] + cost[right][right_color]
                            next_dp[left_color][right_color] = min(next_dp[left_color][right_color], candidate)
            dp = next_dp

        return min(map(min, dp))
