# Optimal solution generated by LLM (doocs/leetcode source unavailable).
class Solution:
    def divisibleGame(self, nums: list[int]) -> int:
        candidates = {2}

        for original in set(nums):
            value = original
            factor = 2
            while factor * factor <= value:
                if value % factor == 0:
                    candidates.add(factor)
                    while value % factor == 0:
                        value //= factor
                factor += 1
            if value > 1:
                candidates.add(value)

        best_difference = None
        best_k = 2

        for k in sorted(candidates):
            signed = nums[0] if nums[0] % k == 0 else -nums[0]
            current = signed
            maximum = signed

            for value in nums[1:]:
                signed = value if value % k == 0 else -value
                current = max(signed, current + signed)
                maximum = max(maximum, current)

            if best_difference is None or maximum > best_difference:
                best_difference = maximum
                best_k = k

        return best_difference * best_k % 1_000_000_007
