# Optimal solution generated by LLM (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def countStableSubsequences(self, nums: List[int]) -> int:
        modulo = 1_000_000_007
        endings = [[0, 0], [0, 0]]

        for value in nums:
            parity = value & 1
            other = parity ^ 1
            new_run_one = (1 + endings[other][0] + endings[other][1]) % modulo
            new_run_two = endings[parity][0]
            endings[parity][0] = (endings[parity][0] + new_run_one) % modulo
            endings[parity][1] = (endings[parity][1] + new_run_two) % modulo

        return sum(map(sum, endings)) % modulo
