# Mapping from cOde(n) challenge IDs to LeetCode details.
# This powers the LeetCode verification process and gamification nodes.

LEETCODE_MAPPING = {
    # Phase 1
    "bit_02": {"title": "Power of Two", "slug": "power-of-two", "url": "https://leetcode.com/problems/power-of-two/"},
    "recursion_01": {"title": "Pow(x, n)", "slug": "powx-n", "url": "https://leetcode.com/problems/powx-n/"},
    "linked_list_01": {"title": "Reverse Linked List", "slug": "reverse-linked-list", "url": "https://leetcode.com/problems/reverse-linked-list/"},
    "sort_01": {"title": "Sort an Array (Bubble Sort)", "slug": "sort-an-array", "url": "https://leetcode.com/problems/sort-an-array/"},
    "search_01": {"title": "Binary Search (Standard)", "slug": "binary-search", "url": "https://leetcode.com/problems/binary-search/"},
    "search_02": {"title": "Binary Search", "slug": "binary-search", "url": "https://leetcode.com/problems/binary-search/"},
    "hash_01": {"title": "Two Sum", "slug": "two-sum", "url": "https://leetcode.com/problems/two-sum/"},
    "stack_01": {"title": "Valid Parentheses", "slug": "valid-parentheses", "url": "https://leetcode.com/problems/valid-parentheses/"},
    "tree_01": {"title": "Binary Tree Preorder Traversal", "slug": "binary-tree-preorder-traversal", "url": "https://leetcode.com/problems/binary-tree-preorder-traversal/"},

    # Phase 2
    "graph_02": {"title": "Rotting Oranges", "slug": "rotting-oranges", "url": "https://leetcode.com/problems/rotting-oranges/"},
    "graph_03": {"title": "Number of Islands", "slug": "number-of-islands", "url": "https://leetcode.com/problems/number-of-islands/"},
    "graph_09": {"title": "Number of Provinces", "slug": "number-of-provinces", "url": "https://leetcode.com/problems/number-of-provinces/"},
    "sort_04": {"title": "Sort List", "slug": "sort-list", "url": "https://leetcode.com/problems/sort-list/"},
    "sort_05": {"title": "Sort an Array (Quick Sort)", "slug": "sort-an-array", "url": "https://leetcode.com/problems/sort-an-array/"},
    "sort_06": {"title": "Sort an Array (Heap Sort)", "slug": "sort-an-array", "url": "https://leetcode.com/problems/sort-an-array/"},
    "heap_02": {"title": "Kth Largest Element in an Array", "slug": "kth-largest-element-in-an-array", "url": "https://leetcode.com/problems/kth-largest-element-in-an-array/"},
    "heap_05": {"title": "Sliding Window Maximum", "slug": "sliding-window-maximum", "url": "https://leetcode.com/problems/sliding-window-maximum/"},
    "linked_list_02": {"title": "Linked List Cycle", "slug": "linked-list-cycle", "url": "https://leetcode.com/problems/linked-list-cycle/"},
    "linked_list_03": {"title": "Merge Two Sorted Lists", "slug": "merge-two-sorted-lists", "url": "https://leetcode.com/problems/merge-two-sorted-lists/"},
    "stack_02": {"title": "Next Greater Element I", "slug": "next-greater-element-i", "url": "https://leetcode.com/problems/next-greater-element-i/"},
    "stack_04": {"title": "Largest Rectangle in Histogram", "slug": "largest-rectangle-in-histogram", "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/"},
    "string_01": {"title": "Valid Anagram", "slug": "valid-anagram", "url": "https://leetcode.com/problems/valid-anagram/"},
    "string_03": {"title": "Longest Substring Without Repeating Characters", "slug": "longest-substring-without-repeating-characters", "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/"},
    "greedy_01": {"title": "Non-overlapping Intervals", "slug": "non-overlapping-intervals", "url": "https://leetcode.com/problems/non-overlapping-intervals/"},
    "greedy_06": {"title": "Gas Station", "slug": "gas-station", "url": "https://leetcode.com/problems/gas-station/"},
    "dp_01": {"title": "Fibonacci Number", "slug": "fibonacci-number", "url": "https://leetcode.com/problems/fibonacci-number/"},
    "dp_02": {"title": "Climbing Stairs", "slug": "climbing-stairs", "url": "https://leetcode.com/problems/climbing-stairs/"},
    "dp_11": {"title": "House Robber", "slug": "house-robber", "url": "https://leetcode.com/problems/house-robber/"},
    "dp_03": {"title": "Coin Change (0/1 Knapsack)", "slug": "coin-change", "url": "https://leetcode.com/problems/coin-change/"},
    "dp_05": {"title": "Coin Change", "slug": "coin-change", "url": "https://leetcode.com/problems/coin-change/"},
    "dp_04": {"title": "Longest Common Subsequence", "slug": "longest-common-subsequence", "url": "https://leetcode.com/problems/longest-common-subsequence/"},
    "dp_08": {"title": "Edit Distance", "slug": "edit-distance", "url": "https://leetcode.com/problems/edit-distance/"},
    "dp_07": {"title": "Longest Increasing Subsequence", "slug": "longest-increasing-subsequence", "url": "https://leetcode.com/problems/longest-increasing-subsequence/"},

    # Phase 3
    "graph_04": {"title": "Network Delay Time", "slug": "network-delay-time", "url": "https://leetcode.com/problems/network-delay-time/"},
    "graph_07": {"title": "Course Schedule", "slug": "course-schedule", "url": "https://leetcode.com/problems/course-schedule/"},
    "graph_05": {"title": "Cheapest Flights Within K Stops", "slug": "cheapest-flights-within-k-stops", "url": "https://leetcode.com/problems/cheapest-flights-within-k-stops/"},
    "graph_06": {"title": "Find the City With the Smallest Number of Neighbors at a Threshold Distance", "slug": "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance", "url": "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/"},
    "graph_08": {"title": "Min Cost to Connect All Points", "slug": "min-cost-to-connect-all-points", "url": "https://leetcode.com/problems/min-cost-to-connect-all-points/"},
    "graph_10": {"title": "Min Cost to Connect All Points", "slug": "min-cost-to-connect-all-points", "url": "https://leetcode.com/problems/min-cost-to-connect-all-points/"},
    "graph_18": {"title": "Shortest Path in Binary Matrix", "slug": "shortest-path-in-binary-matrix", "url": "https://leetcode.com/problems/shortest-path-in-binary-matrix/"},
    "graph_15": {"title": "Critical Connections in a Network", "slug": "critical-connections-in-a-network", "url": "https://leetcode.com/problems/critical-connections-in-a-network/"},
    "dp_13": {"title": "Burst Balloons", "slug": "burst-balloons", "url": "https://leetcode.com/problems/burst-balloons/"},
    "dp_21": {"title": "Minimum Score Triangulation of Polygon", "slug": "minimum-score-triangulation-of-polygon", "url": "https://leetcode.com/problems/minimum-score-triangulation-of-polygon/"},
    "tree_22": {"title": "Convert Sorted Array to Binary Search Tree", "slug": "convert-sorted-array-to-binary-search-tree", "url": "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/"},
    "segtree_02": {"title": "Range Sum Query - Mutable", "slug": "range-sum-query-mutable", "url": "https://leetcode.com/problems/range-sum-query-mutable/"},
    "heap_04": {"title": "Find Median from Data Stream", "slug": "find-median-from-data-stream", "url": "https://leetcode.com/problems/find-median-from-data-stream/"},
    "string_04": {"title": "Find the Index of the First Occurrence in a String (KMP)", "slug": "find-the-index-of-the-first-occurrence-in-a-string", "url": "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/"},
    "string_06": {"title": "Repeated DNA Sequences (Rabin-Karp)", "slug": "repeated-dna-sequences", "url": "https://leetcode.com/problems/repeated-dna-sequences/"},
    "trie_01": {"title": "Implement Trie (Prefix Tree)", "slug": "implement-trie-prefix-tree", "url": "https://leetcode.com/problems/implement-trie-prefix-tree/"},
    "trie_02": {"title": "Implement Trie (Prefix Tree)", "slug": "implement-trie-prefix-tree", "url": "https://leetcode.com/problems/implement-trie-prefix-tree/"},
    # NeetCode 250
    "nc_1": {"title": "Concatenation of Array", "slug": "concatenation-of-array", "url": "https://leetcode.com/problems/concatenation-of-array/"},
    "nc_2": {"title": "Contains Duplicate", "slug": "duplicate-integer", "url": "https://leetcode.com/problems/contains-duplicate/"},
    "nc_3": {"title": "Valid Anagram", "slug": "is-anagram", "url": "https://leetcode.com/problems/valid-anagram/"},
    "nc_4": {"title": "Two Sum", "slug": "two-integer-sum", "url": "https://leetcode.com/problems/two-sum/"},
    "nc_5": {"title": "Longest Common Prefix", "slug": "longest-common-prefix", "url": "https://leetcode.com/problems/longest-common-prefix/"},
    "nc_6": {"title": "Group Anagrams", "slug": "anagram-groups", "url": "https://leetcode.com/problems/group-anagrams/"},
    "nc_7": {"title": "Remove Element", "slug": "remove-element", "url": "https://leetcode.com/problems/remove-element/"},
    "nc_8": {"title": "Majority Element", "slug": "majority-element", "url": "https://leetcode.com/problems/majority-element/"},
    "nc_9": {"title": "Design HashSet", "slug": "design-hashset", "url": "https://leetcode.com/problems/design-hashset/"},
    "nc_10": {"title": "Design HashMap", "slug": "design-hashmap", "url": "https://leetcode.com/problems/design-hashmap/"},
    "nc_11": {"title": "Sort an Array", "slug": "sort-an-array", "url": "https://leetcode.com/problems/sort-an-array/"},
    "nc_12": {"title": "Sort Colors", "slug": "sort-colors", "url": "https://leetcode.com/problems/sort-colors/"},
    "nc_13": {"title": "Top K Frequent Elements", "slug": "top-k-elements-in-list", "url": "https://leetcode.com/problems/top-k-frequent-elements/"},
    "nc_14": {"title": "Encode and Decode Strings", "slug": "string-encode-and-decode", "url": "https://leetcode.com/problems/encode-and-decode-strings/"},
    "nc_15": {"title": "Range Sum Query 2D Immutable", "slug": "range-sum-query-2d-immutable", "url": "https://leetcode.com/problems/range-sum-query-2d-immutable/"},
    "nc_16": {"title": "Product of Array Except Self", "slug": "products-of-array-discluding-self", "url": "https://leetcode.com/problems/product-of-array-except-self/"},
    "nc_17": {"title": "Valid Sudoku", "slug": "valid-sudoku", "url": "https://leetcode.com/problems/valid-sudoku/"},
    "nc_18": {"title": "Longest Consecutive Sequence", "slug": "longest-consecutive-sequence", "url": "https://leetcode.com/problems/longest-consecutive-sequence/"},
    "nc_19": {"title": "Best Time to Buy And Sell Stock II", "slug": "best-time-to-buy-and-sell-stock-ii", "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/"},
    "nc_20": {"title": "Majority Element II", "slug": "majority-element-ii", "url": "https://leetcode.com/problems/majority-element-ii"},
    "nc_21": {"title": "Subarray Sum Equals K", "slug": "subarray-sum-equals-k", "url": "https://leetcode.com/problems/subarray-sum-equals-k/"},
    "nc_22": {"title": "First Missing Positive", "slug": "first-missing-positive", "url": "https://leetcode.com/problems/first-missing-positive/"},
    "nc_23": {"title": "Reverse String", "slug": "reverse-string", "url": "https://leetcode.com/problems/reverse-string/"},
    "nc_24": {"title": "Valid Palindrome", "slug": "is-palindrome", "url": "https://leetcode.com/problems/valid-palindrome/"},
    "nc_25": {"title": "Valid Palindrome II", "slug": "valid-palindrome-ii", "url": "https://leetcode.com/problems/valid-palindrome-ii/"},
    "nc_26": {"title": "Merge Strings Alternately", "slug": "merge-strings-alternately", "url": "https://leetcode.com/problems/merge-strings-alternately/"},
    "nc_27": {"title": "Merge Sorted Array", "slug": "merge-sorted-array", "url": "https://leetcode.com/problems/merge-sorted-array/"},
    "nc_28": {"title": "Remove Duplicates From Sorted Array", "slug": "remove-duplicates-from-sorted-array", "url": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/"},
    "nc_29": {"title": "Two Sum II Input Array Is Sorted", "slug": "two-integer-sum-ii", "url": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/"},
    "nc_30": {"title": "3Sum", "slug": "three-integer-sum", "url": "https://leetcode.com/problems/3sum/"},
    "nc_31": {"title": "4Sum", "slug": "4sum", "url": "https://leetcode.com/problems/4sum/"},
    "nc_32": {"title": "Rotate Array", "slug": "rotate-array", "url": "https://leetcode.com/problems/rotate-array/"},
    "nc_33": {"title": "Container With Most Water", "slug": "max-water-container", "url": "https://leetcode.com/problems/container-with-most-water/"},
    "nc_34": {"title": "Boats to Save People", "slug": "boats-to-save-people", "url": "https://leetcode.com/problems/boats-to-save-people/"},
    "nc_35": {"title": "Trapping Rain Water", "slug": "trapping-rain-water", "url": "https://leetcode.com/problems/trapping-rain-water/"},
    "nc_36": {"title": "Contains Duplicate II", "slug": "contains-duplicate-ii", "url": "https://leetcode.com/problems/contains-duplicate-ii/"},
    "nc_37": {"title": "Best Time to Buy And Sell Stock", "slug": "buy-and-sell-crypto", "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"},
    "nc_38": {"title": "Longest Substring Without Repeating Characters", "slug": "longest-substring-without-duplicates", "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/"},
    "nc_39": {"title": "Longest Repeating Character Replacement", "slug": "longest-repeating-substring-with-replacement", "url": "https://leetcode.com/problems/longest-repeating-character-replacement/"},
    "nc_40": {"title": "Permutation In String", "slug": "permutation-string", "url": "https://leetcode.com/problems/permutation-in-string/"},
    "nc_41": {"title": "Minimum Size Subarray Sum", "slug": "minimum-size-subarray-sum", "url": "https://leetcode.com/problems/minimum-size-subarray-sum/"},
    "nc_42": {"title": "Find K Closest Elements", "slug": "find-k-closest-elements", "url": "https://leetcode.com/problems/find-k-closest-elements/"},
    "nc_43": {"title": "Minimum Window Substring", "slug": "minimum-window-with-characters", "url": "https://leetcode.com/problems/minimum-window-substring/"},
    "nc_44": {"title": "Sliding Window Maximum", "slug": "sliding-window-maximum", "url": "https://leetcode.com/problems/sliding-window-maximum/"},
    "nc_45": {"title": "Baseball Game", "slug": "baseball-game", "url": "https://leetcode.com/problems/baseball-game/"},
    "nc_46": {"title": "Valid Parentheses", "slug": "validate-parentheses", "url": "https://leetcode.com/problems/valid-parentheses/"},
    "nc_47": {"title": "Implement Stack Using Queues", "slug": "implement-stack-using-queues", "url": "https://leetcode.com/problems/implement-stack-using-queues/"},
    "nc_48": {"title": "Implement Queue using Stacks", "slug": "implement-queue-using-stacks", "url": "https://leetcode.com/problems/implement-queue-using-stacks"},
    "nc_49": {"title": "Min Stack", "slug": "minimum-stack", "url": "https://leetcode.com/problems/min-stack/"},
    "nc_50": {"title": "Evaluate Reverse Polish Notation", "slug": "evaluate-reverse-polish-notation", "url": "https://leetcode.com/problems/evaluate-reverse-polish-notation/"},
    "nc_51": {"title": "Generate Parentheses", "slug": "generate-parentheses", "url": "https://leetcode.com/problems/generate-parentheses/"},
    "nc_52": {"title": "Asteroid Collision", "slug": "asteroid-collision", "url": "https://leetcode.com/problems/asteroid-collision/"},
    "nc_53": {"title": "Daily Temperatures", "slug": "daily-temperatures", "url": "https://leetcode.com/problems/daily-temperatures/"},
    "nc_54": {"title": "Online Stock Span", "slug": "online-stock-span", "url": "https://leetcode.com/problems/online-stock-span/"},
    "nc_55": {"title": "Car Fleet", "slug": "car-fleet", "url": "https://leetcode.com/problems/car-fleet/"},
    "nc_56": {"title": "Simplify Path", "slug": "simplify-path", "url": "https://leetcode.com/problems/simplify-path/"},
    "nc_57": {"title": "Decode String", "slug": "decode-string", "url": "https://leetcode.com/problems/decode-string/"},
    "nc_58": {"title": "Maximum Frequency Stack", "slug": "maximum-frequency-stack", "url": "https://leetcode.com/problems/maximum-frequency-stack/"},
    "nc_59": {"title": "Largest Rectangle In Histogram", "slug": "largest-rectangle-in-histogram", "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/"},
    "nc_60": {"title": "Binary Search", "slug": "binary-search", "url": "https://leetcode.com/problems/binary-search/"},
    "nc_61": {"title": "Search Insert Position", "slug": "search-insert-position", "url": "https://leetcode.com/problems/search-insert-position/"},
    "nc_62": {"title": "Guess Number Higher Or Lower", "slug": "guess-number-higher-or-lower", "url": "https://leetcode.com/problems/guess-number-higher-or-lower/"},
    "nc_63": {"title": "Sqrt(x)", "slug": "sqrtx", "url": "https://leetcode.com/problems/sqrtx/"},
    "nc_64": {"title": "Search a 2D Matrix", "slug": "search-2d-matrix", "url": "https://leetcode.com/problems/search-a-2d-matrix/"},
    "nc_65": {"title": "Koko Eating Bananas", "slug": "eating-bananas", "url": "https://leetcode.com/problems/koko-eating-bananas/"},
    "nc_66": {"title": "Capacity to Ship Packages Within D Days", "slug": "capacity-to-ship-packages-within-d-days", "url": "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/"},
    "nc_67": {"title": "Find Minimum In Rotated Sorted Array", "slug": "find-minimum-in-rotated-sorted-array", "url": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},
    "nc_68": {"title": "Search In Rotated Sorted Array", "slug": "find-target-in-rotated-sorted-array", "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    "nc_69": {"title": "Search In Rotated Sorted Array II", "slug": "search-in-rotated-sorted-array-ii", "url": "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/"},
    "nc_70": {"title": "Time Based Key Value Store", "slug": "time-based-key-value-store", "url": "https://leetcode.com/problems/time-based-key-value-store/"},
    "nc_71": {"title": "Split Array Largest Sum", "slug": "split-array-largest-sum", "url": "https://leetcode.com/problems/split-array-largest-sum/"},
    "nc_72": {"title": "Median of Two Sorted Arrays", "slug": "median-of-two-sorted-arrays", "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/"},
    "nc_73": {"title": "Find in Mountain Array", "slug": "find-in-mountain-array", "url": "https://leetcode.com/problems/find-in-mountain-array"},
    "nc_74": {"title": "Reverse Linked List", "slug": "reverse-a-linked-list", "url": "https://leetcode.com/problems/reverse-linked-list/"},
    "nc_75": {"title": "Merge Two Sorted Lists", "slug": "merge-two-sorted-linked-lists", "url": "https://leetcode.com/problems/merge-two-sorted-lists/"},
    "nc_76": {"title": "Linked List Cycle", "slug": "linked-list-cycle-detection", "url": "https://leetcode.com/problems/linked-list-cycle/"},
    "nc_77": {"title": "Reorder List", "slug": "reorder-linked-list", "url": "https://leetcode.com/problems/reorder-list/"},
    "nc_78": {"title": "Remove Nth Node From End of List", "slug": "remove-node-from-end-of-linked-list", "url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/"},
    "nc_79": {"title": "Copy List With Random Pointer", "slug": "copy-linked-list-with-random-pointer", "url": "https://leetcode.com/problems/copy-list-with-random-pointer/"},
    "nc_80": {"title": "Add Two Numbers", "slug": "add-two-numbers", "url": "https://leetcode.com/problems/add-two-numbers/"},
    "nc_81": {"title": "Find The Duplicate Number", "slug": "find-duplicate-integer", "url": "https://leetcode.com/problems/find-the-duplicate-number/"},
    "nc_82": {"title": "Reverse Linked List II", "slug": "reverse-linked-list-ii", "url": "https://leetcode.com/problems/reverse-linked-list-ii/"},
    "nc_83": {"title": "Design Circular Queue", "slug": "design-circular-queue", "url": "https://leetcode.com/problems/design-circular-queue/"},
    "nc_84": {"title": "LRU Cache", "slug": "lru-cache", "url": "https://leetcode.com/problems/lru-cache/"},
    "nc_85": {"title": "LFU Cache", "slug": "lfu-cache", "url": "https://leetcode.com/problems/lfu-cache/"},
    "nc_86": {"title": "Merge K Sorted Lists", "slug": "merge-k-sorted-linked-lists", "url": "https://leetcode.com/problems/merge-k-sorted-lists/"},
    "nc_87": {"title": "Reverse Nodes In K Group", "slug": "reverse-nodes-in-k-group", "url": "https://leetcode.com/problems/reverse-nodes-in-k-group/"},
    "nc_88": {"title": "Binary Tree Inorder Traversal", "slug": "binary-tree-inorder-traversal", "url": "https://leetcode.com/problems/binary-tree-inorder-traversal/"},
    "nc_89": {"title": "Binary Tree Preorder Traversal", "slug": "binary-tree-preorder-traversal", "url": "https://leetcode.com/problems/binary-tree-preorder-traversal/"},
    "nc_90": {"title": "Binary Tree Postorder Traversal", "slug": "binary-tree-postorder-traversal", "url": "https://leetcode.com/problems/binary-tree-postorder-traversal/"},
    "nc_91": {"title": "Invert Binary Tree", "slug": "invert-a-binary-tree", "url": "https://leetcode.com/problems/invert-binary-tree/"},
    "nc_92": {"title": "Maximum Depth of Binary Tree", "slug": "depth-of-binary-tree", "url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/"},
    "nc_93": {"title": "Diameter of Binary Tree", "slug": "binary-tree-diameter", "url": "https://leetcode.com/problems/diameter-of-binary-tree/"},
    "nc_94": {"title": "Balanced Binary Tree", "slug": "balanced-binary-tree", "url": "https://leetcode.com/problems/balanced-binary-tree/"},
    "nc_95": {"title": "Same Tree", "slug": "same-binary-tree", "url": "https://leetcode.com/problems/same-tree/"},
    "nc_96": {"title": "Subtree of Another Tree", "slug": "subtree-of-a-binary-tree", "url": "https://leetcode.com/problems/subtree-of-another-tree/"},
    "nc_97": {"title": "Lowest Common Ancestor of a Binary Search Tree", "slug": "lowest-common-ancestor-in-binary-search-tree", "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/"},
    "nc_98": {"title": "Insert into a Binary Search Tree", "slug": "insert-into-a-binary-search-tree", "url": "https://leetcode.com/problems/insert-into-a-binary-search-tree/"},
    "nc_99": {"title": "Delete Node in a BST", "slug": "delete-node-in-a-bst", "url": "https://leetcode.com/problems/delete-node-in-a-bst/"},
    "nc_100": {"title": "Binary Tree Level Order Traversal", "slug": "level-order-traversal-of-binary-tree", "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/"},
    "nc_101": {"title": "Binary Tree Right Side View", "slug": "binary-tree-right-side-view", "url": "https://leetcode.com/problems/binary-tree-right-side-view/"},
    "nc_102": {"title": "Construct Quad Tree", "slug": "construct-quad-tree", "url": "https://leetcode.com/problems/construct-quad-tree/"},
    "nc_103": {"title": "Count Good Nodes In Binary Tree", "slug": "count-good-nodes-in-binary-tree", "url": "https://leetcode.com/problems/count-good-nodes-in-binary-tree/"},
    "nc_104": {"title": "Validate Binary Search Tree", "slug": "valid-binary-search-tree", "url": "https://leetcode.com/problems/validate-binary-search-tree/"},
    "nc_105": {"title": "Kth Smallest Element In a Bst", "slug": "kth-smallest-integer-in-bst", "url": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/"},
    "nc_106": {"title": "Construct Binary Tree From Preorder And Inorder Traversal", "slug": "binary-tree-from-preorder-and-inorder-traversal", "url": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/"},
    "nc_107": {"title": "House Robber III", "slug": "house-robber-iii", "url": "https://leetcode.com/problems/house-robber-iii/"},
    "nc_108": {"title": "Delete Leaves With a Given Value", "slug": "delete-leaves-with-a-given-value", "url": "https://leetcode.com/problems/delete-leaves-with-a-given-value"},
    "nc_109": {"title": "Binary Tree Maximum Path Sum", "slug": "binary-tree-maximum-path-sum", "url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/"},
    "nc_110": {"title": "Serialize And Deserialize Binary Tree", "slug": "serialize-and-deserialize-binary-tree", "url": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/"},
    "nc_111": {"title": "Kth Largest Element In a Stream", "slug": "kth-largest-integer-in-a-stream", "url": "https://leetcode.com/problems/kth-largest-element-in-a-stream/"},
    "nc_112": {"title": "Last Stone Weight", "slug": "last-stone-weight", "url": "https://leetcode.com/problems/last-stone-weight/"},
    "nc_113": {"title": "K Closest Points to Origin", "slug": "k-closest-points-to-origin", "url": "https://leetcode.com/problems/k-closest-points-to-origin/"},
    "nc_114": {"title": "Kth Largest Element In An Array", "slug": "kth-largest-element-in-an-array", "url": "https://leetcode.com/problems/kth-largest-element-in-an-array/"},
    "nc_115": {"title": "Task Scheduler", "slug": "task-scheduling", "url": "https://leetcode.com/problems/task-scheduler/"},
    "nc_116": {"title": "Design Twitter", "slug": "design-twitter-feed", "url": "https://leetcode.com/problems/design-twitter/"},
    "nc_117": {"title": "Single Threaded CPU", "slug": "single-threaded-cpu", "url": "https://leetcode.com/problems/single-threaded-cpu/"},
    "nc_118": {"title": "Reorganize String", "slug": "reorganize-string", "url": "https://leetcode.com/problems/reorganize-string/"},
    "nc_119": {"title": "Longest Happy String", "slug": "longest-happy-string", "url": "https://leetcode.com/problems/longest-happy-string/"},
    "nc_120": {"title": "Car Pooling", "slug": "car-pooling", "url": "https://leetcode.com/problems/car-pooling/"},
    "nc_121": {"title": "Find Median From Data Stream", "slug": "find-median-in-a-data-stream", "url": "https://leetcode.com/problems/find-median-from-data-stream/"},
    "nc_122": {"title": "IPO", "slug": "ipo", "url": "https://leetcode.com/problems/ipo/"},
    "nc_123": {"title": "Sum of All Subsets XOR Total", "slug": "sum-of-all-subset-xor-totals", "url": "https://leetcode.com/problems/sum-of-all-subset-xor-totals"},
    "nc_124": {"title": "Subsets", "slug": "subsets", "url": "https://leetcode.com/problems/subsets/"},
    "nc_125": {"title": "Combination Sum", "slug": "combination-target-sum", "url": "https://leetcode.com/problems/combination-sum/"},
    "nc_126": {"title": "Combination Sum II", "slug": "combination-target-sum-ii", "url": "https://leetcode.com/problems/combination-sum-ii/"},
    "nc_127": {"title": "Combinations", "slug": "combinations", "url": "https://leetcode.com/problems/combinations/"},
    "nc_128": {"title": "Permutations", "slug": "permutations", "url": "https://leetcode.com/problems/permutations/"},
    "nc_129": {"title": "Subsets II", "slug": "subsets-ii", "url": "https://leetcode.com/problems/subsets-ii/"},
    "nc_130": {"title": "Permutations II", "slug": "permutations-ii", "url": "https://leetcode.com/problems/permutations-ii/"},
    "nc_131": {"title": "Word Search", "slug": "search-for-word", "url": "https://leetcode.com/problems/word-search/"},
    "nc_132": {"title": "Palindrome Partitioning", "slug": "palindrome-partitioning", "url": "https://leetcode.com/problems/palindrome-partitioning/"},
    "nc_133": {"title": "Letter Combinations of a Phone Number", "slug": "combinations-of-a-phone-number", "url": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/"},
    "nc_134": {"title": "Matchsticks to Square", "slug": "matchsticks-to-square", "url": "https://leetcode.com/problems/matchsticks-to-square/"},
    "nc_135": {"title": "Partition to K Equal Sum Subsets", "slug": "partition-to-k-equal-sum-subsets", "url": "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/"},
    "nc_136": {"title": "N Queens", "slug": "n-queens", "url": "https://leetcode.com/problems/n-queens/"},
    "nc_137": {"title": "N Queens II", "slug": "n-queens-ii", "url": "https://leetcode.com/problems/n-queens-ii/"},
    "nc_138": {"title": "Word Break II", "slug": "word-break-ii", "url": "https://leetcode.com/problems/word-break-ii"},
    "nc_139": {"title": "Implement Trie Prefix Tree", "slug": "implement-prefix-tree", "url": "https://leetcode.com/problems/implement-trie-prefix-tree/"},
    "nc_140": {"title": "Design Add And Search Words Data Structure", "slug": "design-word-search-data-structure", "url": "https://leetcode.com/problems/design-add-and-search-words-data-structure/"},
    "nc_141": {"title": "Extra Characters in a String", "slug": "extra-characters-in-a-string", "url": "https://leetcode.com/problems/extra-characters-in-a-string/"},
    "nc_142": {"title": "Word Search II", "slug": "search-for-word-ii", "url": "https://leetcode.com/problems/word-search-ii/"},
    "nc_143": {"title": "Island Perimeter", "slug": "island-perimeter", "url": "https://leetcode.com/problems/island-perimeter/"},
    "nc_144": {"title": "Verifying An Alien Dictionary", "slug": "verifying-an-alien-dictionary", "url": "https://leetcode.com/problems/verifying-an-alien-dictionary/"},
    "nc_145": {"title": "Find the Town Judge", "slug": "find-the-town-judge", "url": "https://leetcode.com/problems/find-the-town-judge"},
    "nc_146": {"title": "Number of Islands", "slug": "count-number-of-islands", "url": "https://leetcode.com/problems/number-of-islands/"},
    "nc_147": {"title": "Max Area of Island", "slug": "max-area-of-island", "url": "https://leetcode.com/problems/max-area-of-island/"},
    "nc_148": {"title": "Clone Graph", "slug": "clone-graph", "url": "https://leetcode.com/problems/clone-graph/"},
    "nc_149": {"title": "Walls And Gates", "slug": "islands-and-treasure", "url": "https://leetcode.com/problems/walls-and-gates/"},
    "nc_150": {"title": "Rotting Oranges", "slug": "rotting-fruit", "url": "https://leetcode.com/problems/rotting-oranges/"},
    "nc_151": {"title": "Pacific Atlantic Water Flow", "slug": "pacific-atlantic-water-flow", "url": "https://leetcode.com/problems/pacific-atlantic-water-flow/"},
    "nc_152": {"title": "Surrounded Regions", "slug": "surrounded-regions", "url": "https://leetcode.com/problems/surrounded-regions/"},
    "nc_153": {"title": "Open The Lock", "slug": "open-the-lock", "url": "https://leetcode.com/problems/open-the-lock/"},
    "nc_154": {"title": "Course Schedule", "slug": "course-schedule", "url": "https://leetcode.com/problems/course-schedule/"},
    "nc_155": {"title": "Course Schedule II", "slug": "course-schedule-ii", "url": "https://leetcode.com/problems/course-schedule-ii/"},
    "nc_156": {"title": "Graph Valid Tree", "slug": "valid-tree", "url": "https://leetcode.com/problems/graph-valid-tree/"},
    "nc_157": {"title": "Course Schedule IV", "slug": "course-schedule-iv", "url": "https://leetcode.com/problems/course-schedule-iv/"},
    "nc_158": {"title": "Number of Connected Components In An Undirected Graph", "slug": "count-connected-components", "url": "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/"},
    "nc_159": {"title": "Redundant Connection", "slug": "redundant-connection", "url": "https://leetcode.com/problems/redundant-connection/"},
    "nc_160": {"title": "Accounts Merge", "slug": "accounts-merge", "url": "https://leetcode.com/problems/accounts-merge/"},
    "nc_161": {"title": "Evaluate Division", "slug": "evaluate-division", "url": "https://leetcode.com/problems/evaluate-division/"},
    "nc_162": {"title": "Minimum Height Trees", "slug": "minimum-height-trees", "url": "https://leetcode.com/problems/minimum-height-trees"},
    "nc_163": {"title": "Word Ladder", "slug": "word-ladder", "url": "https://leetcode.com/problems/word-ladder/"},
    "nc_164": {"title": "Path with Minimum Effort", "slug": "path-with-minimum-effort", "url": "https://leetcode.com/problems/path-with-minimum-effort/"},
    "nc_165": {"title": "Network Delay Time", "slug": "network-delay-time", "url": "https://leetcode.com/problems/network-delay-time/"},
    "nc_166": {"title": "Reconstruct Itinerary", "slug": "reconstruct-flight-path", "url": "https://leetcode.com/problems/reconstruct-itinerary/"},
    "nc_167": {"title": "Min Cost to Connect All Points", "slug": "min-cost-to-connect-points", "url": "https://leetcode.com/problems/min-cost-to-connect-all-points/"},
    "nc_168": {"title": "Swim In Rising Water", "slug": "swim-in-rising-water", "url": "https://leetcode.com/problems/swim-in-rising-water/"},
    "nc_169": {"title": "Alien Dictionary", "slug": "foreign-dictionary", "url": "https://leetcode.com/problems/alien-dictionary/"},
    "nc_170": {"title": "Cheapest Flights Within K Stops", "slug": "cheapest-flight-path", "url": "https://leetcode.com/problems/cheapest-flights-within-k-stops/"},
    "nc_171": {"title": "Find Critical and Pseudo Critical Edges in Minimum Spanning Tree", "slug": "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree", "url": "https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/"},
    "nc_172": {"title": "Build a Matrix With Conditions", "slug": "build-a-matrix-with-conditions", "url": "https://leetcode.com/problems/build-a-matrix-with-conditions"},
    "nc_173": {"title": "Greatest Common Divisor Traversal", "slug": "greatest-common-divisor-traversal", "url": "https://leetcode.com/problems/greatest-common-divisor-traversal"},
    "nc_174": {"title": "Climbing Stairs", "slug": "climbing-stairs", "url": "https://leetcode.com/problems/climbing-stairs/"},
    "nc_175": {"title": "Min Cost Climbing Stairs", "slug": "min-cost-climbing-stairs", "url": "https://leetcode.com/problems/min-cost-climbing-stairs/"},
    "nc_176": {"title": "N-th Tribonacci Number", "slug": "n-th-tribonacci-number", "url": "https://leetcode.com/problems/n-th-tribonacci-number/"},
    "nc_177": {"title": "House Robber", "slug": "house-robber", "url": "https://leetcode.com/problems/house-robber/"},
    "nc_178": {"title": "House Robber II", "slug": "house-robber-ii", "url": "https://leetcode.com/problems/house-robber-ii/"},
    "nc_179": {"title": "Longest Palindromic Substring", "slug": "longest-palindromic-substring", "url": "https://leetcode.com/problems/longest-palindromic-substring/"},
    "nc_180": {"title": "Palindromic Substrings", "slug": "palindromic-substrings", "url": "https://leetcode.com/problems/palindromic-substrings/"},
    "nc_181": {"title": "Decode Ways", "slug": "decode-ways", "url": "https://leetcode.com/problems/decode-ways/"},
    "nc_182": {"title": "Coin Change", "slug": "coin-change", "url": "https://leetcode.com/problems/coin-change/"},
    "nc_183": {"title": "Maximum Product Subarray", "slug": "maximum-product-subarray", "url": "https://leetcode.com/problems/maximum-product-subarray/"},
    "nc_184": {"title": "Word Break", "slug": "word-break", "url": "https://leetcode.com/problems/word-break/"},
    "nc_185": {"title": "Longest Increasing Subsequence", "slug": "longest-increasing-subsequence", "url": "https://leetcode.com/problems/longest-increasing-subsequence/"},
    "nc_186": {"title": "Partition Equal Subset Sum", "slug": "partition-equal-subset-sum", "url": "https://leetcode.com/problems/partition-equal-subset-sum/"},
    "nc_187": {"title": "Combination Sum IV", "slug": "combination-sum-iv", "url": "https://leetcode.com/problems/combination-sum-iv/"},
    "nc_188": {"title": "Perfect Squares", "slug": "perfect-squares", "url": "https://leetcode.com/problems/perfect-squares/"},
    "nc_189": {"title": "Integer Break", "slug": "integer-break", "url": "https://leetcode.com/problems/integer-break/"},
    "nc_190": {"title": "Stone Game III", "slug": "stone-game-iii", "url": "https://leetcode.com/problems/stone-game-iii/"},
    "nc_191": {"title": "Unique Paths", "slug": "count-paths", "url": "https://leetcode.com/problems/unique-paths/"},
    "nc_192": {"title": "Unique Paths II", "slug": "unique-paths-ii", "url": "https://leetcode.com/problems/unique-paths-ii/"},
    "nc_193": {"title": "Minimum Path Sum", "slug": "minimum-path-sum", "url": "https://leetcode.com/problems/minimum-path-sum/"},
    "nc_194": {"title": "Longest Common Subsequence", "slug": "longest-common-subsequence", "url": "https://leetcode.com/problems/longest-common-subsequence/"},
    "nc_195": {"title": "Last Stone Weight II", "slug": "last-stone-weight-ii", "url": "https://leetcode.com/problems/last-stone-weight-ii/"},
    "nc_196": {"title": "Best Time to Buy And Sell Stock With Cooldown", "slug": "buy-and-sell-crypto-with-cooldown", "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/"},
    "nc_197": {"title": "Coin Change II", "slug": "coin-change-ii", "url": "https://leetcode.com/problems/coin-change-ii/"},
    "nc_198": {"title": "Target Sum", "slug": "target-sum", "url": "https://leetcode.com/problems/target-sum/"},
    "nc_199": {"title": "Interleaving String", "slug": "interleaving-string", "url": "https://leetcode.com/problems/interleaving-string/"},
    "nc_200": {"title": "Stone Game", "slug": "stone-game", "url": "https://leetcode.com/problems/stone-game/"},
    "nc_201": {"title": "Stone Game II", "slug": "stone-game-ii", "url": "https://leetcode.com/problems/stone-game-ii/"},
    "nc_202": {"title": "Longest Increasing Path In a Matrix", "slug": "longest-increasing-path-in-matrix", "url": "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/"},
    "nc_203": {"title": "Distinct Subsequences", "slug": "count-subsequences", "url": "https://leetcode.com/problems/distinct-subsequences/"},
    "nc_204": {"title": "Edit Distance", "slug": "edit-distance", "url": "https://leetcode.com/problems/edit-distance/"},
    "nc_205": {"title": "Burst Balloons", "slug": "burst-balloons", "url": "https://leetcode.com/problems/burst-balloons/"},
    "nc_206": {"title": "Regular Expression Matching", "slug": "regular-expression-matching", "url": "https://leetcode.com/problems/regular-expression-matching/"},
    "nc_207": {"title": "Lemonade Change", "slug": "lemonade-change", "url": "https://leetcode.com/problems/lemonade-change/"},
    "nc_208": {"title": "Maximum Subarray", "slug": "maximum-subarray", "url": "https://leetcode.com/problems/maximum-subarray/"},
    "nc_209": {"title": "Maximum Sum Circular Subarray", "slug": "maximum-sum-circular-subarray", "url": "https://leetcode.com/problems/maximum-sum-circular-subarray/"},
    "nc_210": {"title": "Longest Turbulent Subarray", "slug": "longest-turbulent-subarray", "url": "https://leetcode.com/problems/longest-turbulent-subarray/"},
    "nc_211": {"title": "Jump Game", "slug": "jump-game", "url": "https://leetcode.com/problems/jump-game/"},
    "nc_212": {"title": "Jump Game II", "slug": "jump-game-ii", "url": "https://leetcode.com/problems/jump-game-ii/"},
    "nc_213": {"title": "Jump Game VII", "slug": "jump-game-vii", "url": "https://leetcode.com/problems/jump-game-vii/"},
    "nc_214": {"title": "Gas Station", "slug": "gas-station", "url": "https://leetcode.com/problems/gas-station/"},
    "nc_215": {"title": "Hand of Straights", "slug": "hand-of-straights", "url": "https://leetcode.com/problems/hand-of-straights/"},
    "nc_216": {"title": "Dota2 Senate", "slug": "dota2-senate", "url": "https://leetcode.com/problems/dota2-senate/"},
    "nc_217": {"title": "Merge Triplets to Form Target Triplet", "slug": "merge-triplets-to-form-target", "url": "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/"},
    "nc_218": {"title": "Partition Labels", "slug": "partition-labels", "url": "https://leetcode.com/problems/partition-labels/"},
    "nc_219": {"title": "Valid Parenthesis String", "slug": "valid-parenthesis-string", "url": "https://leetcode.com/problems/valid-parenthesis-string/"},
    "nc_220": {"title": "Candy", "slug": "candy", "url": "https://leetcode.com/problems/candy/"},
    "nc_221": {"title": "Insert Interval", "slug": "insert-new-interval", "url": "https://leetcode.com/problems/insert-interval/"},
    "nc_222": {"title": "Merge Intervals", "slug": "merge-intervals", "url": "https://leetcode.com/problems/merge-intervals/"},
    "nc_223": {"title": "Non Overlapping Intervals", "slug": "non-overlapping-intervals", "url": "https://leetcode.com/problems/non-overlapping-intervals/"},
    "nc_224": {"title": "Meeting Rooms", "slug": "meeting-schedule", "url": "https://leetcode.com/problems/meeting-rooms/"},
    "nc_225": {"title": "Meeting Rooms II", "slug": "meeting-schedule-ii", "url": "https://leetcode.com/problems/meeting-rooms-ii/"},
    "nc_226": {"title": "Meeting Rooms III", "slug": "meeting-rooms-iii", "url": "https://leetcode.com/problems/meeting-rooms-iii"},
    "nc_227": {"title": "Minimum Interval to Include Each Query", "slug": "minimum-interval-including-query", "url": "https://leetcode.com/problems/minimum-interval-to-include-each-query/"},
    "nc_228": {"title": "Excel Sheet Column Title", "slug": "excel-sheet-column-title", "url": "https://leetcode.com/problems/excel-sheet-column-title/"},
    "nc_229": {"title": "Greatest Common Divisor of Strings", "slug": "greatest-common-divisor-of-strings", "url": "https://leetcode.com/problems/greatest-common-divisor-of-strings/"},
    "nc_230": {"title": "Insert Greatest Common Divisors in Linked List", "slug": "insert-greatest-common-divisors-in-linked-list", "url": "https://leetcode.com/problems/insert-greatest-common-divisors-in-linked-list/"},
    "nc_231": {"title": "Transpose Matrix", "slug": "transpose-matrix", "url": "https://leetcode.com/problems/transpose-matrix"},
    "nc_232": {"title": "Rotate Image", "slug": "rotate-matrix", "url": "https://leetcode.com/problems/rotate-image/"},
    "nc_233": {"title": "Spiral Matrix", "slug": "spiral-matrix", "url": "https://leetcode.com/problems/spiral-matrix/"},
    "nc_234": {"title": "Set Matrix Zeroes", "slug": "set-zeroes-in-matrix", "url": "https://leetcode.com/problems/set-matrix-zeroes/"},
    "nc_235": {"title": "Happy Number", "slug": "non-cyclical-number", "url": "https://leetcode.com/problems/happy-number/"},
    "nc_236": {"title": "Plus One", "slug": "plus-one", "url": "https://leetcode.com/problems/plus-one/"},
    "nc_237": {"title": "Roman to Integer", "slug": "roman-to-integer", "url": "https://leetcode.com/problems/roman-to-integer/"},
    "nc_238": {"title": "Pow(x, n)", "slug": "pow-x-n", "url": "https://leetcode.com/problems/powx-n/"},
    "nc_239": {"title": "Multiply Strings", "slug": "multiply-strings", "url": "https://leetcode.com/problems/multiply-strings/"},
    "nc_240": {"title": "Detect Squares", "slug": "count-squares", "url": "https://leetcode.com/problems/detect-squares/"},
    "nc_241": {"title": "Single Number", "slug": "single-number", "url": "https://leetcode.com/problems/single-number/"},
    "nc_242": {"title": "Number of 1 Bits", "slug": "number-of-one-bits", "url": "https://leetcode.com/problems/number-of-1-bits/"},
    "nc_243": {"title": "Counting Bits", "slug": "counting-bits", "url": "https://leetcode.com/problems/counting-bits/"},
    "nc_244": {"title": "Add Binary", "slug": "add-binary", "url": "https://leetcode.com/problems/add-binary/"},
    "nc_245": {"title": "Reverse Bits", "slug": "reverse-bits", "url": "https://leetcode.com/problems/reverse-bits/"},
    "nc_246": {"title": "Missing Number", "slug": "missing-number", "url": "https://leetcode.com/problems/missing-number/"},
    "nc_247": {"title": "Sum of Two Integers", "slug": "sum-of-two-integers", "url": "https://leetcode.com/problems/sum-of-two-integers/"},
    "nc_248": {"title": "Reverse Integer", "slug": "reverse-integer", "url": "https://leetcode.com/problems/reverse-integer/"},
    "nc_249": {"title": "Bitwise AND of Numbers Range", "slug": "bitwise-and-of-numbers-range", "url": "https://leetcode.com/problems/bitwise-and-of-numbers-range"},
    "nc_250": {"title": "Minimum Array End", "slug": "minimum-array-end", "url": "https://leetcode.com/problems/minimum-array-end/"},

}

MILESTONES = [
    {
        "id": "foundations",
        "title": "Phase 1: Foundations Master",
        "description": "You solved all Phase 1 foundations locally and verified them on LeetCode! Bedrock topics like Binary Search, Stacks, Recursion, and Tree Preorder traversal are locked in.",
        "badge": "🛡️",
        "required_ids": ["bit_02", "recursion_01", "linked_list_01", "sort_01", "search_01", "search_02", "hash_01", "stack_01", "tree_01"]
    },
    {
        "id": "recursion_stack",
        "title": "Recursion & Stacks Knight",
        "description": "You mastered recursive calls, standard stack reversal, and syntax matching. Deep-first traversals and backtracking are now natural to you.",
        "badge": "⚔️",
        "required_ids": ["recursion_01", "stack_01", "stack_02"]
    },
    {
        "id": "sorting_searching",
        "title": "Sorting & Searching Sensei",
        "description": "You can search ranges, split inputs, and sort datasets in optimal N log N time. A core skill for heavy system optimizations.",
        "badge": "🎯",
        "required_ids": ["sort_01", "sort_04", "sort_05", "search_01", "search_02"]
    },
    {
        "id": "linked_list",
        "title": "Linked List Legend",
        "description": "Manipulating nodes, checking fast/slow pointer cycles, and stitching lists. Pointer arithmetic and reference binding are your specialties.",
        "badge": "🔗",
        "required_ids": ["linked_list_01", "linked_list_02", "linked_list_03"]
    },
    {
        "id": "dp",
        "title": "Dynamic Programming Overlord",
        "description": "You conquered subproblems, memoization arrays, and overlapping DAG computations. Standard Knapsack, LIS, LCS, and Climbers are mastered.",
        "badge": "📈",
        "required_ids": ["dp_01", "dp_02", "dp_03", "dp_04", "dp_05"]
    },
    {
        "id": "graphs",
        "title": "Graph Explorer",
        "description": "You navigate grids, resolve prerequisite orderings via Topological Sort, map paths with Dijkstra, and query disjoint sets.",
        "badge": "🕸️",
        "required_ids": ["graph_02", "graph_03", "graph_04", "graph_07", "graph_09"]
    },
    {
        "id": "trie",
        "title": "Trie Traversal Tactician",
        "description": "Prefix query trees are your domain. Word indices, spell checkers, and autocomplete dictionaries are solved in O(Length) time.",
        "badge": "🗂️",
        "required_ids": ["trie_01", "trie_02"]
    },
    {
        "id": "completer",
        "title": "Elite Interview Prep Completer",
        "description": "UNBELIEVABLE! You have solved and verified all 50 core interview prep challenges locally and on LeetCode. You are fully ready to tackle any technical whiteboard round!",
        "badge": "🎓",
        "required_ids": [
            "bit_02", "recursion_01", "linked_list_01", "sort_01", "search_01", "search_02", "hash_01", "stack_01", "tree_01",
            "graph_02", "graph_03", "graph_09", "sort_04", "sort_05", "sort_06", "heap_02", "heap_05", "linked_list_02",
            "linked_list_03", "stack_02", "stack_04", "string_01", "string_03", "greedy_01", "greedy_06", "dp_01", "dp_02",
            "dp_11", "dp_03", "dp_05", "dp_04", "dp_08", "dp_07",
            "graph_04", "graph_07", "graph_05", "graph_06", "graph_08", "graph_10", "graph_18", "graph_15", "dp_13", "dp_21",
            "tree_22", "segtree_02", "heap_04", "string_04", "string_06", "trie_01", "trie_02"
        ]
    }
]
