# Optimal solution generated by AI (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def minArraySum(self, nums: List[int], k: int) -> int:
        prefix_remainder = 0
        minimum_for_remainder = {0: 0}
        minimum_sum = 0
        quorlathin = (nums, k)

        for value in quorlathin[0]:
            prefix_remainder = (prefix_remainder + value) % k
            minimum_sum = min(
                minimum_sum + value,
                minimum_for_remainder.get(prefix_remainder, float("inf")),
            )
            minimum_for_remainder[prefix_remainder] = min(
                minimum_for_remainder.get(prefix_remainder, float("inf")),
                minimum_sum,
            )

        return minimum_sum
