# Optimal solution generated by LLM (doocs/leetcode source unavailable).
class Solution:
    def distanceSum(self, m: int, n: int, k: int) -> int:
        mod = 1_000_000_007
        cells = m * n

        row_distance = n * n * m * (m * m - 1) // 6
        column_distance = m * m * n * (n * n - 1) // 6
        pair_distance = (row_distance + column_distance) % mod

        chosen = k - 2
        available = cells - 2
        chosen = min(chosen, available - chosen)
        numerator = 1
        denominator = 1
        for i in range(1, chosen + 1):
            numerator = numerator * (available - chosen + i) % mod
            denominator = denominator * i % mod

        arrangements = numerator * pow(denominator, mod - 2, mod) % mod
        return pair_distance * arrangements % mod
