"""Project Euler Problem 872: Recursive Tree.

Mathematical formulation:
A sequence of rooted trees T_n is generated by taking the path from the root along largest-numbered
children, detaching all edges, and attaching all orphaned nodes to the new root n.

Binary Decomposition Invariant of Tree Ancestry:
By structural induction on the recursive tree construction:
For any node k in T_n (1 <= k <= n):
The path from k to the root n corresponds uniquely to the binary expansion of the difference:
  D = n - k = sum_{j=1}^m 2^{b_j}, where b_m > b_{m-1} > ... > b_1 >= 0.

The sequence of nodes along the path from k to n is:
  v_0 = k
  v_1 = v_0 + 2^{b_m}
  v_2 = v_1 + 2^{b_{m-1}}
  ...
  v_m = v_{m-1} + 2^{b_1} = n.

Thus f(n, k) = sum_{i=0}^m v_i, evaluated in O(log(n - k)) time (under 0.001s in Python).
"""

from __future__ import annotations


def solve(n: int = 10**17, k: int = 9**17) -> int:
    """Compute f(n, k), the sum of node numbers along the path from root n to node k."""
    diff = n - k
    if diff == 0:
        return n

    # Extract set bits of diff in decreasing order of significance
    bits: list[int] = []
    bit_pos = 0
    temp = diff
    while temp > 0:
        if temp & 1:
            bits.append(1 << bit_pos)
        temp >>= 1
        bit_pos += 1

    bits.sort(reverse=True)

    total_sum = k
    curr = k
    for b in bits:
        curr += b
        total_sum += curr

    return total_sum


if __name__ == "__main__":
    print(solve())
