"""Project Euler Problem 360: Scary Sphere.

Find the sum of the Manhattan distances of all points with integer coordinates on the surface of C(10^10) to the origin.
"""

from collections import Counter
from math import factorial


def solve(r: int = 10**10) -> int:
    """Find S(10^10) for the sum of Manhattan distances of all lattice points on C(r) to origin."""
    if r <= 0:
        return 0

    # Factor r = 2^e2 * 5^e5
    e2 = 0
    temp = r
    while temp > 0 and temp % 2 == 0:
        e2 += 1
        temp //= 2
    e5 = 0
    while temp > 0 and temp % 5 == 0:
        e5 += 1
        temp //= 5

    # 6 elementary integer rotation matrices from SO(3, Z[1/5]) generated by Hurwitz prime quaternions
    moves = [
        lambda x, y, z: (5 * x, 3 * y - 4 * z, 4 * y + 3 * z),
        lambda x, y, z: (5 * x, 3 * y + 4 * z, -4 * y + 3 * z),
        lambda x, y, z: (3 * x + 4 * z, 5 * y, -4 * x + 3 * z),
        lambda x, y, z: (3 * x - 4 * z, 5 * y, 4 * x + 3 * z),
        lambda x, y, z: (3 * x - 4 * y, 4 * x + 3 * y, 5 * z),
        lambda x, y, z: (3 * x + 4 * y, -4 * x + 3 * y, 5 * z),
    ]

    def get_orbit_weight(x: int, y: int, z: int) -> int:
        """Compute the number of unique signed permutation lattice points in the orbit of (x, y, z)."""
        non_zeros = sum(1 for v in (x, y, z) if v > 0)
        counts = Counter((x, y, z)).values()
        perm_denom = 1
        for c in counts:
            perm_denom *= factorial(c)
        perms = 6 // perm_denom
        return (1 << non_zeros) * perms

    # Generate all points on sphere of radius 5^e5 via 6-matrix tree
    curr = {(1, 0, 0)}
    for _ in range(e5):
        nxt = set()
        for x, y, z in curr:
            for m in moves:
                nxt.add(m(x, y, z))
        curr = nxt

    # Group into canonical absolute-sorted orbits (x >= y >= z >= 0)
    orbits = set()
    for x, y, z in curr:
        ax, ay, az = sorted((abs(x), abs(y), abs(z)), reverse=True)
        orbits.add((ax, ay, az))

    total_s = 0
    for ax, ay, az in orbits:
        w = get_orbit_weight(ax, ay, az)
        total_s += w * (ax + ay + az)

    # Scale by 2^e2 for radius r = 2^e2 * 5^e5
    return (2**e2) * total_s


if __name__ == "__main__":
    print(solve())
