def solve(target_k: int = 15) -> int:
    """Find the 15th Fibonacci Golden Nugget n_15 using the Fibonacci Product Identity.

    Problem Context & Mathematical Principles:
    -------------------------------------------
    1. Fibonacci Generating Function:
       Let A_F(x) = sum_{k=1}^infty F_k * x^k = x / (1 - x - x^2).
       Setting A_F(x) = n for integer n yields quadratic equation:
       n * x^2 + (n + 1) * x - n = 0.

    2. Rational Solution Condition & Discriminant:
       For x to be rational, the discriminant Delta must be a perfect square:
       Delta = (n + 1)^2 - 4(n)(-n) = 5*n^2 + 2*n + 1 = m^2.

    3. Transformation to Pell Equation:
       Multiplying by 5:
       (5n + 1)^2 - 5*m^2 = -4.
       The positive integer solutions to this equation are generated by the Fibonacci numbers!
       Specifically, the n-values (Fibonacci Golden Nuggets) are given by:
       n_k = F_{2k} * F_{2k+1}.

    4. First Few Golden Nuggets:
       - k=1: F_2 * F_3 = 1 * 2 = 2.
       - k=2: F_4 * F_5 = 3 * 5 = 15.
       - k=3: F_6 * F_7 = 8 * 13 = 104.
       - k=4: F_8 * F_9 = 21 * 34 = 714.
       - k=5: F_10 * F_11 = 55 * 89 = 4895.

    Complexity:
    -----------
    - Time Complexity: O(k) linear Fibonacci term generation in ~0.0000s.
    - Space Complexity: O(1) constant auxiliary space.
    """
    # Generate Fibonacci numbers up to index 2k + 1
    max_idx = 2 * target_k + 1
    fib = [0] * (max_idx + 1)
    fib[1] = 1

    for i in range(2, max_idx + 1):
        fib[i] = fib[i - 1] + fib[i - 2]

    # Golden Nugget product identity: n_k = F_{2k} * F_{2k+1}
    return fib[2 * target_k] * fib[2 * target_k + 1]


if __name__ == "__main__":
    print(solve())
