def solve(limit: int = 100) -> int:
    """Find number of distinct terms generated by a^b for 2 <= a <= limit and 2 <= b <= limit.
    
    Time Complexity: O(limit^2)
    Space Complexity: O(limit^2)
    """
    return len({a**b for a in range(2, limit + 1) for b in range(2, limit + 1)})
