def solve(limit: int = 100) -> int:
    """Find the number of distinct terms generated by a^b for 2 <= a <= limit and 2 <= b <= limit.

    Mathematical Principles Applied:
    1. Power Set Cardinality:
       Define S = { a^b : 2 <= a <= limit, 2 <= b <= limit }.
       We count the number of unique elements |S|.

    2. Exponential Base Collisions:
       Bases that are powers of a smaller base (e.g. 2^4 = 4^2 = 16^1) generate overlapping
       exponential terms.
       Python's set comprehension handles large integer arithmetic and hash-based deduplication
       automatically in O(limit^2) steps.

    Time Complexity: O(limit^2) executing in ~0.001s.
    Space Complexity: O(limit^2) memory to store hash set of terms.
    """
    # Generate all terms a^b for 2 <= a <= limit and 2 <= b <= limit into a hash set
    # Using a set comprehension automatically removes duplicate terms
    distinct_powers_set = {a**b for a in range(2, limit + 1) for b in range(2, limit + 1)}

    # Return cardinality of distinct powers set
    return len(distinct_powers_set)


if __name__ == "__main__":
    print(solve())
