# Optimal solution generated by AI (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def minZeroArray(self, nums: List[int], queries: List[List[int]]) -> int:
        length = len(nums)
        possible = [1] * length
        masks = [(1 << (target + 1)) - 1 for target in nums]
        satisfied = [target == 0 for target in nums]
        remaining = sum(not state for state in satisfied)

        if remaining == 0:
            return 0

        for query_index, (left, right, value) in enumerate(queries, start=1):
            for index in range(left, right + 1):
                if satisfied[index]:
                    continue
                possible[index] |= possible[index] << value
                possible[index] &= masks[index]
                if (possible[index] >> nums[index]) & 1:
                    satisfied[index] = True
                    remaining -= 1

            if remaining == 0:
                return query_index

        return -1
