# Optimal solution generated by AI (doocs/leetcode source unavailable).
class Solution:
    def maxProfit(self, n: int, edges: List[List[int]], score: List[int]) -> int:
        prerequisites = [0] * n
        for source, target in edges:
            prerequisites[target] |= 1 << source

        dp = [-1] * (1 << n)
        dp[0] = 0
        valid_masks = [0]

        for placed in range(n):
            next_valid_masks = []
            for mask in valid_masks:
                for node in range(n):
                    bit = 1 << node
                    if not mask & bit and mask & prerequisites[node] == prerequisites[node]:
                        next_mask = mask | bit
                        if dp[next_mask] == -1:
                            next_valid_masks.append(next_mask)
                        candidate = dp[mask] + (placed + 1) * score[node]
                        if candidate > dp[next_mask]:
                            dp[next_mask] = candidate
            valid_masks = next_valid_masks

        return dp[-1]
