# Optimal solution generated by LLM (doocs/leetcode source unavailable).
class Solution:
    def lexSmallest(self, s: str) -> str:
        n = len(s)
        reversed_s = s[::-1]
        sources = (s, reversed_s)
        base = 911382323
        moduli = (1_000_000_007, 1_000_000_009)

        powers = []
        hashes = []
        for modulus in moduli:
            power = [1] * (n + 1)
            for index in range(n):
                power[index + 1] = power[index] * base % modulus
            source_hashes = []
            for text in sources:
                prefix = [0] * (n + 1)
                for index, character in enumerate(text):
                    prefix[index + 1] = (prefix[index] * base + ord(character) - ord("a") + 1) % modulus
                source_hashes.append(prefix)
            powers.append(power)
            hashes.append(source_hashes)

        def substring_hash(
            modulus_index: int,
            source: int,
            left: int,
            right: int,
        ) -> int:
            modulus = moduli[modulus_index]
            prefix = hashes[modulus_index][source]
            return (prefix[right] - prefix[left] * powers[modulus_index][right - left]) % modulus

        # A candidate is (source1, left1, right1, source2, left2, right2).
        def prefix_hash(candidate: tuple[int, ...], length: int, modulus_index: int) -> int:
            source1, left1, right1, source2, left2, _ = candidate
            first_length = right1 - left1
            if length <= first_length:
                return substring_hash(modulus_index, source1, left1, left1 + length)
            remainder = length - first_length
            modulus = moduli[modulus_index]
            return (
                substring_hash(modulus_index, source1, left1, right1) * powers[modulus_index][remainder]
                + substring_hash(modulus_index, source2, left2, left2 + remainder)
            ) % modulus

        def character_at(candidate: tuple[int, ...], index: int) -> str:
            source1, left1, right1, source2, left2, _ = candidate
            first_length = right1 - left1
            if index < first_length:
                return sources[source1][left1 + index]
            return sources[source2][left2 + index - first_length]

        def is_smaller(candidate: tuple[int, ...], current: tuple[int, ...]) -> bool:
            low = 0
            high = n
            while low < high:
                middle = (low + high + 1) // 2
                if prefix_hash(candidate, middle, 0) == prefix_hash(current, middle, 0) and prefix_hash(
                    candidate, middle, 1
                ) == prefix_hash(current, middle, 1):
                    low = middle
                else:
                    high = middle - 1
            return low < n and character_at(candidate, low) < character_at(current, low)

        best = (0, 0, n, 0, n, n)
        for k in range(1, n + 1):
            candidate = (1, n - k, n, 0, k, n)
            if is_smaller(candidate, best):
                best = candidate
        for start in range(n):
            candidate = (0, 0, start, 1, 0, n - start)
            if is_smaller(candidate, best):
                best = candidate

        source1, left1, right1, source2, left2, right2 = best
        return sources[source1][left1:right1] + sources[source2][left2:right2]
