"""Project Euler 288: An Enormous Factorial

Find NF(61, 10^7) mod 61^10, where NF(p, q) is the number of factors p in N(p, q)!,
with N(p, q) = sum_{n=0}^q T_n * p^n generated by Blum Blum Shub PRNG mod 50515093.
"""

from __future__ import annotations


def solve(p: int = 61, q: int = 10**7, k_exp: int = 10) -> str:
    """Calculates NF(p, q) mod p^k_exp using Legendre's formula.

    By Legendre's formula:
        NF(p, q) = sum_{k=1}^q floor(N(p, q) / p^k) = sum_{n=1}^q T_n * (p^n - 1) / (p - 1)

    Modulo p^k_exp:
      - For 1 <= n < k_exp: the coefficient is exactly (p^n - 1) // (p - 1).
      - For n >= k_exp: sum_{j=0}^{n-1} p^j = sum_{j=0}^{k_exp-1} p^j (mod p^k_exp)
        is constant C = (p^k_exp - 1) // (p - 1).
    Thus:
        NF(p, q) = sum_{n=1}^{k_exp-1} T_n * coeff_n + C * (sum_{n=k_exp}^q T_n) (mod p^k_exp)
    """
    mod = p**k_exp
    c_const = (p**k_exp - 1) // (p - 1)
    m_bbs = 50515093

    s = 290797
    total = 0
    sum_t_large = 0

    for n in range(q + 1):
        t = s % p
        if 1 <= n < k_exp:
            coeff = (p**n - 1) // (p - 1)
            total = (total + t * coeff) % mod
        elif n >= k_exp:
            sum_t_large += t

        s = (s * s) % m_bbs

    total = (total + sum_t_large * c_const) % mod
    return str(total)


if __name__ == "__main__":
    print(solve())
