# Optimal solution generated by LLM (doocs/leetcode source unavailable).
class Solution:
    def palindromePath(
        self,
        n: int,
        edges: list[list[int]],
        s: str,
        queries: list[str],
    ) -> list[bool]:
        graph = [[] for _ in range(n)]
        for first, second in edges:
            graph[first].append(second)
            graph[second].append(first)

        node_mask = [1 << (ord(character) - ord("a")) for character in s]
        parent = [0] * n
        depth = [0] * n
        entry = [0] * n
        exit_time = [0] * n
        initial_root_mask = [0] * n

        timer = 0
        stack = [(0, 0, False)]
        while stack:
            node, previous, leaving = stack.pop()
            if leaving:
                exit_time[node] = timer
                continue

            parent[node] = previous
            if node != 0:
                depth[node] = depth[previous] + 1
                initial_root_mask[node] = initial_root_mask[previous] ^ node_mask[node]
            else:
                initial_root_mask[node] = node_mask[node]

            entry[node] = timer
            timer += 1
            stack.append((node, previous, True))
            for neighbor in reversed(graph[node]):
                if neighbor != previous:
                    stack.append((neighbor, node, False))

        ancestors = [parent]
        for _ in range(1, n.bit_length()):
            previous_level = ancestors[-1]
            ancestors.append([previous_level[previous_level[node]] for node in range(n)])

        def lowest_common_ancestor(first: int, second: int) -> int:
            if depth[first] < depth[second]:
                first, second = second, first

            difference = depth[first] - depth[second]
            level = 0
            while difference:
                if difference & 1:
                    first = ancestors[level][first]
                difference >>= 1
                level += 1

            if first == second:
                return first

            for level in range(len(ancestors) - 1, -1, -1):
                if ancestors[level][first] != ancestors[level][second]:
                    first = ancestors[level][first]
                    second = ancestors[level][second]

            return parent[first]

        difference_tree = [0] * (n + 1)

        def apply_from(index: int, mask: int) -> None:
            index += 1
            while index <= n:
                difference_tree[index] ^= mask
                index += index & -index

        def accumulated_at(index: int) -> int:
            result = 0
            index += 1
            while index:
                result ^= difference_tree[index]
                index -= index & -index
            return result

        answers = []
        for operation in queries:
            parts = operation.split()
            if parts[0] == "update":
                node = int(parts[1])
                replacement = 1 << (ord(parts[2]) - ord("a"))
                difference = node_mask[node] ^ replacement
                if difference:
                    apply_from(entry[node], difference)
                    if exit_time[node] < n:
                        apply_from(exit_time[node], difference)
                    node_mask[node] = replacement
            else:
                first = int(parts[1])
                second = int(parts[2])
                ancestor = lowest_common_ancestor(first, second)
                path_mask = (
                    initial_root_mask[first]
                    ^ accumulated_at(entry[first])
                    ^ initial_root_mask[second]
                    ^ accumulated_at(entry[second])
                    ^ node_mask[ancestor]
                )
                answers.append(path_mask & (path_mask - 1) == 0)

        return answers
