# Optimal solution generated by LLM (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def bowlSubarrays(self, nums: List[int]) -> int:
        answer = 0
        stack: list[tuple[int, int]] = []

        for right, value in enumerate(nums):
            while stack and stack[-1][0] < value:
                _, left = stack.pop()
                if right - left >= 2:
                    answer += 1

            if stack and right - stack[-1][1] >= 2:
                answer += 1

            stack.append((value, right))

        return answer
