// Optimal solution generated by AI (doocs/leetcode source unavailable).
/**
 * @param {Function} queryMultiple
 * @param {number} t
 * @return {void}
 */
var QueryBatcher = function(queryMultiple, t) {
    this.queryMultiple = queryMultiple;
    this.t = t;
    this.queue = [];
    this.throttled = false;
};

QueryBatcher.prototype.flush = function() {
    if (this.throttled || this.queue.length === 0) {
        return;
    }

    this.throttled = true;
    const batch = this.queue;
    this.queue = [];

    setTimeout(() => {
        this.throttled = false;
        this.flush();
    }, this.t);

    this.queryMultiple(batch.map(item => item.key)).then(values => {
        values.forEach((value, index) => batch[index].resolve(value));
    });
};

/**
 * @param {string} key
 * @return {Promise<string>}
 */
QueryBatcher.prototype.getValue = function(key) {
    return new Promise(resolve => {
        this.queue.push({ key, resolve });
        this.flush();
    });
};
