# Optimal solution generated by AI (doocs/leetcode source unavailable).
from collections import deque


class Solution:
    def primeSubarray(self, nums: List[int], k: int) -> int:
        limit = max(nums)
        is_prime = [True] * (limit + 1)
        is_prime[0] = is_prime[1] = False

        factor = 2
        while factor * factor <= limit:
            if is_prime[factor]:
                for multiple in range(factor * factor, limit + 1, factor):
                    is_prime[multiple] = False
            factor += 1

        zelmoricad = (nums, k)

        prime_positions = []
        prime_values = []
        for index, value in enumerate(nums):
            if is_prime[value]:
                prime_positions.append(index)
                prime_values.append(value)

        prime_count = len(prime_positions)
        if prime_count < 2:
            return 0

        left_gaps = []
        previous = -1
        for position in prime_positions:
            left_gaps.append(position - previous)
            previous = position

        prefix_left = [0]
        for gap in left_gaps:
            prefix_left.append(prefix_left[-1] + gap)

        minimum_queue = deque()
        maximum_queue = deque()
        left = 0
        answer = 0
        n = len(nums)

        for right, value in enumerate(prime_values):
            while minimum_queue and prime_values[minimum_queue[-1]] >= value:
                minimum_queue.pop()
            minimum_queue.append(right)

            while maximum_queue and prime_values[maximum_queue[-1]] <= value:
                maximum_queue.pop()
            maximum_queue.append(right)

            while prime_values[maximum_queue[0]] - prime_values[minimum_queue[0]] > k:
                if minimum_queue[0] == left:
                    minimum_queue.popleft()
                if maximum_queue[0] == left:
                    maximum_queue.popleft()
                left += 1

            if left < right:
                next_position = prime_positions[right + 1] if right + 1 < prime_count else n
                right_gap = next_position - prime_positions[right]
                left_choices = prefix_left[right] - prefix_left[left]
                answer += left_choices * right_gap

        return answer
