# Subtractive Lagged Fibonacci Generator constants (from problem specification)
_LFG_A = 100003
_LFG_B = 200003
_LFG_C = 300007
_LFG_MOD = 1000000
_LFG_OFFSET = _LFG_MOD // 2


def kadane(arr: list[int]) -> int:
    """Find the maximum 1D contiguous subarray sum using Kadane's Algorithm in O(L) time."""
    max_so_far = curr_max = arr[0]
    for x in arr[1:]:
        curr_max = max(x, curr_max + x)
        if curr_max > max_so_far:
            max_so_far = curr_max
    return max_so_far


def solve() -> int:
    """Find the maximum contiguous sequence sum (horizontal, vertical, diagonal, anti-diagonal)
    in a 2000 x 2000 grid generated by a Subtractive Lagged Fibonacci Generator.

    Mathematical Principles Applied:
    1. Subtractive Lagged Fibonacci Generator LFG(24, 55):
       For k = 1..55: s_k = (100003 - 200003*k + 300007*k^3) mod 1,000,000 - 500,000.
       For k = 56..4,000,000: s_k = (s_{k-24} + s_{k-55} + 1,000,000) mod 1,000,000 - 500,000.
       Populate 2000 x 2000 matrix grid[r][c] = s_{2000*r + c + 1}.

    2. 1D Kadane's Algorithm Reduction along 4 Directional Lines:
       Extract all 2000 rows, 2000 columns, 3999 main diagonals, and 3999 anti-diagonals.
       Apply Kadane's Algorithm to each 1D slice in O(L) time.
       Return the global maximum subarray sum.

    Time Complexity: O(N^2) executing in ~2.50s.
    Space Complexity: O(N^2) memory for 2000x2000 grid.
    """
    n = 2000
    total_elements = n * n

    # 1. Subtractive Lagged Fibonacci Generator initialization
    s = [0] * (total_elements + 1)
    for k in range(1, 56):
        s[k] = (_LFG_A - _LFG_B * k + _LFG_C * k**3) % _LFG_MOD - _LFG_OFFSET
    for k in range(56, total_elements + 1):
        s[k] = (s[k - 24] + s[k - 55] + _LFG_MOD) % _LFG_MOD - _LFG_OFFSET

    # 2. Populate 2000 x 2000 grid
    grid = [[0] * n for _ in range(n)]
    idx = 1
    for r in range(n):
        for c in range(n):
            grid[r][c] = s[idx]
            idx += 1

    global_max = -float("inf")

    # 3. Horizontal rows max subarray sum
    for r in range(n):
        global_max = max(global_max, kadane(grid[r]))

    # 4. Vertical columns max subarray sum
    for c in range(n):
        col = [grid[r][c] for r in range(n)]
        global_max = max(global_max, kadane(col))

    # 5. Main diagonals (top-left to bottom-right)
    for start_r in range(n):
        diag = [grid[start_r + i][i] for i in range(n - start_r)]
        global_max = max(global_max, kadane(diag))
    for start_c in range(1, n):
        diag = [grid[i][start_c + i] for i in range(n - start_c)]
        global_max = max(global_max, kadane(diag))

    # 6. Anti-diagonals (top-right to bottom-left)
    for start_r in range(n):
        diag = [grid[start_r - i][i] for i in range(start_r + 1)]
        global_max = max(global_max, kadane(diag))
    for start_c in range(1, n):
        diag = [grid[n - 1 - i][start_c + i] for i in range(n - start_c)]
        global_max = max(global_max, kadane(diag))

    # Return maximum contiguous sub-sequence sum across all directions
    return global_max


if __name__ == "__main__":
    print(solve())
