def kadane(arr: list[int]) -> int:
    """Find maximum 1D contiguous subarray sum."""
    max_so_far = curr_max = arr[0]
    for x in arr[1:]:
        curr_max = max(x, curr_max + x)
        if curr_max > max_so_far:
            max_so_far = curr_max
    return max_so_far


def solve() -> int:
    """Find maximum contiguous sequence sum in 2000x2000 grid generated by Lagged Fibonacci Generator.
    
    Time Complexity: O(N^2)
    Space Complexity: O(N^2)
    """
    n = 2000
    total_elements = n * n

    # 1. Lagged Fibonacci Generator
    s = [0] * (total_elements + 1)
    for k in range(1, 56):
        s[k] = (100003 - 200003 * k + 300007 * k**3) % 1000000 - 500000
    for k in range(56, total_elements + 1):
        s[k] = (s[k - 24] + s[k - 55] + 1000000) % 1000000 - 500000

    # 2. Build N x N grid
    grid = [[0] * n for _ in range(n)]
    idx = 1
    for r in range(n):
        for c in range(n):
            grid[r][c] = s[idx]
            idx += 1

    global_max = -float('inf')

    # 3. Horizontal lines
    for r in range(n):
        global_max = max(global_max, kadane(grid[r]))

    # 4. Vertical lines
    for c in range(n):
        col = [grid[r][c] for r in range(n)]
        global_max = max(global_max, kadane(col))

    # 5. Main Diagonals (top-left to bottom-right)
    for start_r in range(n):
        diag = [grid[start_r + i][i] for i in range(n - start_r)]
        global_max = max(global_max, kadane(diag))
    for start_c in range(1, n):
        diag = [grid[i][start_c + i] for i in range(n - start_c)]
        global_max = max(global_max, kadane(diag))

    # 6. Anti-Diagonals (top-right to bottom-left)
    for start_r in range(n):
        diag = [grid[start_r - i][i] for i in range(start_r + 1)]
        global_max = max(global_max, kadane(diag))
    for start_c in range(1, n):
        diag = [grid[n - 1 - i][start_c + i] for i in range(n - start_c)]
        global_max = max(global_max, kadane(diag))

    return global_max
