# Optimal solution generated by AI (doocs/leetcode source unavailable).
class Solution:
    def countCells(self, grid: List[List[str]], pattern: str) -> int:
        rows = len(grid)
        columns = len(grid[0])
        length = len(pattern)

        prefix = [0] * length
        matched = 0
        for index in range(1, length):
            while matched and pattern[index] != pattern[matched]:
                matched = prefix[matched - 1]
            if pattern[index] == pattern[matched]:
                matched += 1
            prefix[index] = matched

        def covered(text):
            difference = [0] * (len(text) + 1)
            matched = 0
            for index, character in enumerate(text):
                while matched and character != pattern[matched]:
                    matched = prefix[matched - 1]
                if character == pattern[matched]:
                    matched += 1
                if matched == length:
                    start = index - length + 1
                    difference[start] += 1
                    difference[index + 1] -= 1
                    matched = prefix[matched - 1]

            result = [False] * len(text)
            active = 0
            for index in range(len(text)):
                active += difference[index]
                result[index] = active > 0
            return result

        horizontal = "".join("".join(row) for row in grid)
        vertical = "".join(grid[row][column] for column in range(columns) for row in range(rows))
        horizontal_cells = covered(horizontal)
        vertical_cells = covered(vertical)

        answer = 0
        for row in range(rows):
            for column in range(columns):
                horizontal_index = row * columns + column
                vertical_index = column * rows + row
                if horizontal_cells[horizontal_index] and vertical_cells[vertical_index]:
                    answer += 1
        return answer
