def solve(target_count: int = 30) -> int:
    """Find the sum of the first 30 Modified Fibonacci Golden Nuggets.

    Mathematical Principles Applied:
    1. Generating Function A(x) for Modified Fibonacci Sequence:
       A(x) = sum_{k=1}^inf G_k * x^k = (x + 3x^2) / (1 - x - x^2).
       For A(x) = n to be a positive integer, setting (x + 3x^2) / (1 - x - x^2) = n.
       Cross-multiplying: (n + 3)*x^2 + (n + 1)*x - n = 0.
       Discriminant of quadratic in x MUST be a perfect square:
       Discriminant = (n + 1)^2 + 4n(n + 3) = 5n^2 + 14n + 1 = y^2.

    2. Hyperbolic Diophantine Transformation:
       Multiply 5n^2 + 14n + 1 = y^2 by 5 and complete the square:
       (5n + 7)^2 - 5y^2 = 44.
       Let K = 5n + 7. Then K^2 - 5y^2 = 44 (Pell-type Diophantine Equation).

    3. Fundamental Matrix Recurrence Generator:
       Solutions (K_k, y_k) are generated by fundamental Pell solutions (9, 4) applied to 6 base seeds:
       K_{next} = 9 * K + 20 * y
       y_{next} = 4 * K + 9 * y.
       Extract n = (K - 7) / 5 for valid n > 0, sort the deduplicated set, and sum the first 30 terms.

    Time Complexity: O(target_count) linear execution in ~0.001s.
    Space Complexity: O(target_count) memory for nuggets set.
    """
    # Base seed pairs (K0, y0) solving K^2 - 5*y^2 = 44
    seeds = [
        (7, 1),
        (8, 2),
        (13, 5),
        (17, 7),
        (32, 14),
        (43, 19),
        (-7, 1),
        (-8, 2),
        (-13, 5),
        (-17, 7),
        (-32, 14),
        (-43, 19),
    ]

    n_set = set()

    # Generate Pell solutions across all 12 seed branches
    for k0, y0 in seeds:
        k, y = k0, y0
        for _ in range(target_count + 5):
            # Check if K = 5n + 7 gives integer n > 0
            if (k - 7) % 5 == 0:
                n = (k - 7) // 5
                if n > 0:
                    n_set.add(n)
            # Advance Pell recurrence via matrix multiplication (9, 20 / 4, 9)
            k_next = 9 * k + 20 * y
            y_next = 4 * k + 9 * y
            k, y = k_next, y_next

    # Sort generated Modified Golden Nuggets in ascending order
    sorted_n = sorted(n_set)

    # Return total sum of the first 30 Modified Fibonacci Golden Nuggets
    return sum(sorted_n[:target_count])


if __name__ == "__main__":
    print(solve())
