import json
import re
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LEETCODE_ROOT = REPO_ROOT / "dsa" / "leetcode"
INDEX_PATH = LEETCODE_ROOT / "index.json"

DOOCS_ROOT = REPO_ROOT / "temp_doocs" / "solution"
KAMYU_ROOT = REPO_ROOT / "temp_kamyu104"

with open(INDEX_PATH, "r", encoding="utf-8") as f:
    questions = json.load(f)["questions"]

# Build map of doocs folders by frontend_id
doocs_set = set()
if DOOCS_ROOT.is_dir():
    for range_dir in DOOCS_ROOT.iterdir():
        if range_dir.is_dir():
            for q_dir in range_dir.iterdir():
                if q_dir.is_dir():
                    prefix = q_dir.name.split(".")[0]
                    if prefix.isdigit():
                        fid = int(prefix)
                        # Check if any Solution.* file exists inside
                        if list(q_dir.glob("Solution.*")):
                            doocs_set.add(fid)

# Build map of kamyu104 slugs
kamyu_set = set()
for lang_folder in ["Python", "MySQL", "Shell", "JavaScript", "C++"]:
    folder_path = KAMYU_ROOT / lang_folder
    if folder_path.is_dir():
        for f in folder_path.glob("*.*"):
            kamyu_set.add(f.stem)

deleted_competitive_count = 0
llm_optimal_count = 0

DISCLAIMER_COMMENT = {
    ".py": "# Optimal solution generated by LLM (doocs/leetcode source unavailable).\n",
    ".js": "// Optimal solution generated by LLM (doocs/leetcode source unavailable).\n",
    ".sql": "-- Optimal solution generated by LLM (doocs/leetcode source unavailable).\n",
    ".sh": "# Optimal solution generated by LLM (doocs/leetcode source unavailable).\n"
}

for q in questions:
    fid = int(q["frontend_id"])
    slug = q["slug"]
    folder_name = f"{fid:04d}_{slug}"
    pkg_dir = LEETCODE_ROOT / folder_name
    if not pkg_dir.is_dir():
        continue

    manifest_path = pkg_dir / "solution_variants.json"
    manifest = {}
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            manifest = {}

    # 1. Enforce Competitive Variant Rule
    comp_dir = pkg_dir / "variants" / "competitive"
    has_kamyu = slug in kamyu_set

    if not has_kamyu:
        # Delete competitive variant folder if present
        if comp_dir.exists():
            shutil.rmtree(comp_dir)
            deleted_competitive_count += 1

        # Remove competitive from solution_variants.json
        if "variants" in manifest:
            manifest["variants"] = [v for v in manifest["variants"] if v.get("id") != "competitive"]
            if manifest.get("default_variant") == "competitive":
                manifest["default_variant"] = "optimal"
            manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    else:
        # Ensure competitive variant is in solution_variants.json
        if "variants" in manifest:
            v_ids = [v.get("id") for v in manifest["variants"]]
            if "competitive" not in v_ids:
                manifest["variants"].append({
                    "id": "competitive",
                    "label": "Competitive",
                    "kind": "competitive",
                    "directory": "variants/competitive",
                    "summary": "Micro-optimized competitive programming solution from kamyu104/LeetCode-Solutions.",
                    "time_complexity": "O(N)",
                    "space_complexity": "O(N)"
                })
                manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    # 2. Enforce Optimal LLM Disclaimer Rule
    has_doocs = fid in doocs_set
    optimal_dir = pkg_dir / "variants" / "optimal"
    if not has_doocs and optimal_dir.is_dir():
        sol_files = list(optimal_dir.glob("solution.*"))
        for sol_file in sol_files:
            ext = sol_file.suffix.lower()
            if ext in DISCLAIMER_COMMENT:
                disc = DISCLAIMER_COMMENT[ext]
                content = sol_file.read_text(encoding="utf-8", errors="ignore")
                if "generated by LLM" not in content:
                    sol_file.write_text(disc + content, encoding="utf-8")
                    llm_optimal_count += 1

        # Update manifest summary for optimal variant if missing doocs
        if "variants" in manifest:
            for v in manifest["variants"]:
                if v.get("id") == "optimal":
                    v["summary"] = "Optimal solution generated by LLM (doocs/leetcode source unavailable)."
            manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

print(f"Deleted competitive variants without kamyu104 source: {deleted_competitive_count}")
print(f"Added LLM disclaimers to optimal solutions without doocs source: {llm_optimal_count}")
