import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LEETCODE_ROOT = REPO_ROOT / "dsa" / "leetcode"

solution_files_updated = 0
manifests_updated = 0

for pkg_dir in LEETCODE_ROOT.iterdir():
    if not pkg_dir.is_dir() or pkg_dir.name.startswith("_"):
        continue

    # 1. Update solution files in variants/optimal
    optimal_dir = pkg_dir / "variants" / "optimal"
    if optimal_dir.is_dir():
        for sol_file in optimal_dir.glob("solution.*"):
            content = sol_file.read_text(encoding="utf-8", errors="ignore")
            if "generated by LLM" in content:
                new_content = content.replace("generated by LLM", "generated by AI")
                sol_file.write_text(new_content, encoding="utf-8")
                solution_files_updated += 1

    # 2. Update solution_variants.json
    manifest_path = pkg_dir / "solution_variants.json"
    if manifest_path.is_file():
        content = manifest_path.read_text(encoding="utf-8", errors="ignore")
        if "generated by LLM" in content:
            new_content = content.replace("generated by LLM", "generated by AI")
            manifest_path.write_text(new_content, encoding="utf-8")
            manifests_updated += 1

print(f"Updated solution files: {solution_files_updated}")
print(f"Updated manifests: {manifests_updated}")
