# Optimal solution generated by AI (doocs/leetcode source unavailable).
class Solution:
    def maxScore(self, n: int, edges: List[List[int]]) -> int:
        path_score = n * (n + 1) * (2 * n + 1) // 6 - 2 * n + 1
        return path_score + (2 if len(edges) == n else 0)
