# Optimal solution generated by LLM (doocs/leetcode source unavailable).
from typing import List


class Solution:
    def sumCounts(self, nums: List[int]) -> int:
        mod = 1_000_000_007
        n = len(nums)
        sums = [0] * (4 * n)
        square_sums = [0] * (4 * n)
        lazy = [0] * (4 * n)

        def apply(node: int, left: int, right: int, increment: int) -> None:
            length = right - left + 1
            square_sums[node] = (square_sums[node] + 2 * increment * sums[node] + increment * increment * length) % mod
            sums[node] = (sums[node] + increment * length) % mod
            lazy[node] += increment

        def push(node: int, left: int, right: int) -> None:
            if lazy[node] == 0 or left == right:
                return
            middle = (left + right) // 2
            apply(node * 2, left, middle, lazy[node])
            apply(node * 2 + 1, middle + 1, right, lazy[node])
            lazy[node] = 0

        def add(
            node: int,
            left: int,
            right: int,
            query_left: int,
            query_right: int,
        ) -> None:
            if query_left <= left and right <= query_right:
                apply(node, left, right, 1)
                return

            push(node, left, right)
            middle = (left + right) // 2
            if query_left <= middle:
                add(node * 2, left, middle, query_left, query_right)
            if middle < query_right:
                add(node * 2 + 1, middle + 1, right, query_left, query_right)
            sums[node] = (sums[node * 2] + sums[node * 2 + 1]) % mod
            square_sums[node] = (square_sums[node * 2] + square_sums[node * 2 + 1]) % mod

        last_position = {}
        answer = 0

        for right, value in enumerate(nums):
            update_left = last_position.get(value, -1) + 1
            add(1, 0, n - 1, update_left, right)
            last_position[value] = right
            answer = (answer + square_sums[1]) % mod

        return answer
