def solve(n_cuboids: int = 50000) -> int:
    """Find combined volume of 50000 axis-aligned cuboids generated by Lagged Fibonacci Generator.
    
    Time Complexity: O(Z_max * (N_active * log N_active + N_active * dx_avg))
    Space Complexity: O(N_cuboids + X_max)
    """
    S = [0] * (6 * n_cuboids + 1)
    for k in range(1, 56):
        k_val = k
        term = (
            100003 - 200003 * k_val + 300007 * k_val * k_val * k_val
        ) % 1000000
        if term < 0:
            term += 1000000
        S[k] = term
    for k in range(56, 6 * n_cuboids + 1):
        S[k] = (S[k - 24] + S[k - 55]) % 1000000

    N = n_cuboids
    cuboids = []
    for n in range(1, N + 1):
        x0 = S[6 * n - 5] % 10000
        y0 = S[6 * n - 4] % 10000
        z0 = S[6 * n - 3] % 10000
        dx = 1 + (S[6 * n - 2] % 399)
        dy = 1 + (S[6 * n - 1] % 399)
        dz = 1 + (S[6 * n] % 399)
        cuboids.append((x0, x0 + dx, y0, y0 + dy, z0, z0 + dz))

    MAX_Z = 10500
    z_start = [[] for _ in range(MAX_Z)]
    z_end = [[] for _ in range(MAX_Z)]

    for i in range(N):
        z_start[cuboids[i][4]].append(i)
        z_end[cuboids[i][5]].append(i)

    active = [False] * N
    total_volume = 0

    count_x = [0] * 10500

    for z in range(MAX_Z):
        for idx in z_end[z]:
            active[idx] = False
        for idx in z_start[z]:
            active[idx] = True

        y_events = []
        for i in range(N):
            if active[i]:
                y_events.append(
                    (cuboids[i][2], 1, cuboids[i][0], cuboids[i][1])
                )
                y_events.append(
                    (cuboids[i][3], -1, cuboids[i][0], cuboids[i][1])
                )

        if not y_events:
            continue

        y_events.sort(key=lambda ev: ev[0])

        prev_y = y_events[0][0]
        active_x_count = 0
        layer_area = 0

        for y, ev_type, x1, x2 in y_events:
            dy = y - prev_y
            if dy > 0:
                layer_area += active_x_count * dy
                prev_y = y

            for x in range(x1, x2):
                if ev_type == 1:
                    if count_x[x] == 0:
                        active_x_count += 1
                    count_x[x] += 1
                else:
                    count_x[x] -= 1
                    if count_x[x] == 0:
                        active_x_count -= 1

        total_volume += layer_area

    return total_volume
