from array import array


def solve(limit: int = 40000000, target_len: int = 25) -> int:
    """Find the sum of all primes < 40,000,000 that generate a totient chain of length 25.

    Problem Context & Mathematical Principles:
    -------------------------------------------
    1. Euler's Totient Sieve:
       Pre-allocate array phi of size LIMIT = 40,000,000 using 32-bit unsigned integers.
       Sieve totient values: phi(n) = n * prod_{p | n} (1 - 1/p) in O(LIMIT * log log LIMIT) time.

    2. Totient Chain Dynamic Programming:
       A totient chain is generated by iteratively applying phi until reaching 1:
           n -> phi(n) -> phi(phi(n)) -> ... -> 1.
       Chain length L[n] satisfies:
           L[1] = 1
           L[n] = 1 + L[phi(n)] for n >= 2.

    3. Simultaneous Chain Calculation & Prime Filtering:
       In a single forward pass over n = 2..LIMIT-1:
       - Compute L[n] = 1 + L[phi[n]] in O(1) time using a compact bytearray.
       - If phi[n] == n - 1 (meaning n is prime) and L[n] == 25:
         accumulate n into the total sum.

    Complexity:
    -----------
    - Time Complexity: O(limit * log(log(limit))) operations (~16s for limit = 40,000,000).
    - Space Complexity: O(limit) auxiliary memory using 32-bit array + bytearray (~200 MB).
    """
    # Pre-allocate 32-bit array for Euler's totient function
    phi = array("I", range(limit))

    for i in range(2, limit):
        if phi[i] == i:  # i is prime
            for j in range(i, limit, i):
                phi[j] -= phi[j] // i

    # Dynamic programming for chain lengths L and prime filtering in a single pass
    L = bytearray(limit)
    L[1] = 1
    ans = 0

    for i in range(2, limit):
        p_i = phi[i]
        l_i = L[p_i] + 1
        L[i] = l_i

        if p_i == i - 1:  # i is prime
            if l_i == target_len:
                ans += i

    # Return total sum of primes generating a totient chain of length 25
    return ans


if __name__ == "__main__":
    print(solve())
