# Optimal solution generated by LLM (doocs/leetcode source unavailable).
class Solution:
    def countSubstrings(self, s: str) -> int:
        counts = [[]] + [[0] * modulus for modulus in range(1, 10)]
        answer = 0

        for character in s:
            digit = ord(character) - ord("0")
            for modulus in range(1, 10):
                next_counts = [0] * modulus
                next_counts[digit % modulus] = 1
                for remainder, amount in enumerate(counts[modulus]):
                    next_remainder = (remainder * 10 + digit) % modulus
                    next_counts[next_remainder] += amount
                counts[modulus] = next_counts

            if digit != 0:
                answer += counts[digit][0]

        return answer
