import math


def solve(limit: int = 100000000) -> int:
    """Find the number of right-angled triangles with perimeter < limit (100,000,000) that allow central hole tiling.

    Mathematical Principles Applied:
    1. Central Square Hole Geometry:
       Four identical right triangles with sides (a, b, c) arranged in a square outline (c x c)
       leave a central square hole of side length |b - a|.
       The central hole can tile the c x c square iff c is divisible by |b - a|:
       c % |b - a| == 0.

    2. Euclid's Pythagorean Triple Parameterization:
       Primitive Pythagorean triples are generated by coprime m > n of opposite parity:
       a = m^2 - n^2, b = 2mn, c = m^2 + n^2.
       Primitive perimeter P_0 = 2m(m + n).

    3. Multiplicity Scaling for Non-Primitive Triangles:
       If primitive triple (a, b, c) allows central hole tiling (c % |b - a| == 0),
       then ALL scaled multiples (k*a, k*b, k*c) also allow tiling!
       The number of valid non-primitive triangles with perimeter < limit is:
       k_max = (limit - 1) // P_0.

    Time Complexity: O(sqrt(limit)) executing in ~0.05s.
    Space Complexity: O(1) constant auxiliary space.
    """
    total_count = 0
    max_m = int((limit // 2) ** 0.5)

    # Outer loop for parameter m
    for m in range(2, max_m + 1):
        for n in range(1, m):
            # Primitive triple condition: coprime m, n of opposite parity
            if (m - n) % 2 == 1 and math.gcd(m, n) == 1:
                a = m * m - n * n
                b = 2 * m * n
                c = m * m + n * n

                perim = a + b + c
                # Prune if primitive perimeter exceeds limit = 10^8
                if perim >= limit:
                    break

                hole = abs(b - a)
                # Tiling condition: hypotenuse c is divisible by hole side length |b - a|
                if c % hole == 0:
                    # Add number of valid scaled multiples k * perim < 10^8
                    total_count += (limit - 1) // perim

    # Return total count of valid triangles with perimeter < 100,000,000
    return total_count


if __name__ == "__main__":
    print(solve())
