# Optimal solution generated by LLM (doocs/leetcode source unavailable).
class Solution:
    def resultArray(self, nums: List[int], k: int) -> List[int]:
        result = [0] * k
        ending = [0] * k

        for value in nums:
            remainder = value % k
            next_ending = [0] * k
            next_ending[remainder] += 1

            for previous, count in enumerate(ending):
                next_ending[(previous * remainder) % k] += count

            for x, count in enumerate(next_ending):
                result[x] += count

            ending = next_ending

        return result
